[BOOKMARKS]


[PROFILES]

current = default

[VIDEO]

layout = ZX 48K:448:312:64:56:64:16:64:8:120:256:192
scrFormat = png
scrCount = 50
scrInterval = 1
colorLevel = 192
fullscreen = no
doublesize = yes
border = full

[ROMSETS]

name = ZX Spectrum 48K
rom = 48.rom:0:16:0

[SOUND]

enabled = yes
soundsys = SDL
dontmute = yes
rate = 44100
volume.beep = 100
volume.tape = 100
volume.ay = 100
volume.gs = 100
