[MACHINE]

current = ZX48K
memory = 48
contio = yes
contmem = yes

[BETADISK]

enabled = no

[SOUND]
psg.count = 0
psg.type = 1
psg.frq = 1.750000
gs = no

[ROMSET]

current = ZX Spectrum 48K
reset = basic48

[VIDEO]

geometry = ZX 48K
contPattern = 1

