[MACHINE]

current = PentEvo
memory = 4096
cpu.type = Z80
cpu.frq = 3500000
frq.mul = 1.000000
scrp.wait = no
contio = no
contmem = no

[ROMSET]

current = ZX Evo (BaseConf)
reset = basic128

[VIDEO]

geometry = Pentagon
4t-border = no
ULAplus = no
contPattern = 0
earlyTiming = no
DDpal = no
palette = xpeccy.txt

[SOUND]

psg.count = 1
psg.type = 2
psg.frq = 1.750000
psg.stereo = 1
psg.separation = 75
gs = no
gs.reset = yes
gs.stereo = 1
soundrive_type = 1
saa = no

[TAPE]

speed = 100

[DISK]

type = 1

[INPUT]

mouse = yes
mouse.wheel = no
mouse.swapButtons = no
mouse.sensitivity = 1.000000
joy.extbuttons = yes
gamepad.map = kempston.pad

[IDE]

iface = 5
master.type = 0
slave.type = 0
