[machine]
name    = ATM Turbo 2+
family  = clone
hw      = ATM2
memory  = 1024
cpu.frq = 3500000

[video]
geometry = ULA.ATM2

[sound]
psg.type  = ym
soundrive = covox

[storage]
disk = trdos
ide  = atm

[input]
mouse       = yes
joy.buttons = yes

[rom]
rom0 = atm2.rom
gs   = gs105b.rom
font = sgen.rom
