[machine]
name      = ZX Evolution (BaseConf)
family    = evolution
hw        = Baseconf
memory    = 4096
ram.cold  = aa55
ram.noise = 2
cpu.frq   = 3500000

[video]
geometry = ULA.Pentagon

[sound]
psg.count  = 2
psg.type   = ym
psg.frq    = 1.75
psg.stereo = abc
soundrive  = covox

[storage]
disk = trdos
ide  = nemo-evo

[input]
kbd.scantab = at
mouse       = yes
mouse.wheel = yes
joy.buttons = yes

[rom]
rom0 = zxevo-fe.rom
gs   = gs105b.rom
font = sgen.rom
