[machine]
name    = ZX Evolution (BaseConf)
family  = evolution
hw      = Baseconf
memory  = 4096
cpu.frq = 3500000

[video]
geometry = ULA.Pentagon

[storage]
disk = trdos

[input]
kbd.scantab = at

[rom]
rom0 = zxevo-fe.rom
gs   = gs105b.rom
font = sgen.rom
