[machine]
name    = ZX Evolution (TSConf)
family  = evolution
hw      = TSConf
memory  = 4096
cpu.frq = 3500000

[video]
geometry = ULA.TSConf

[storage]
disk = trdos

[input]
kbd.scantab = at
mouse       = yes
joy.buttons = yes

[rom]
rom0 = tsconf.rom
gs   = gs105b.rom
font = sgen.rom
