[machine]
name    = ZX Evolution (BaseConf)
family  = clone
hw      = Baseconf
memory  = 4096
cpu.frq = 3500000

[video]
geometry = Pentagon

[storage]
disk = trdos

[rom]
rom0 = zxevo-fe.rom
gs   = gs105b.rom
font = sgen.rom
