[machine]
name     = ZX Evolution (TSConf)
family   = evolution
hw       = TSConf
memory   = 4096
ram.cold = aa55
cpu.frq  = 3500000

[video]
geometry = ULA.TSConf

[sound]
psg.count = 2
psg.type  = ym
soundrive = covox

[storage]
disk = trdos
ide  = nemo-evo

[input]
kbd.scantab = at
mouse       = yes
mouse.wheel = yes
joy.buttons = yes

[rom]
rom0 = tsconf.rom
gs   = gs105b.rom
font = sgen.rom
