[machine]
name    = ZX Evolution (TSConf)
family  = evolution
hw      = TSConf
memory  = 4096
cpu.frq = 3500000

[video]
geometry = TSConf

[storage]
disk = trdos

[rom]
rom0 = tsconf.rom
gs   = gs105b.rom
font = sgen.rom
