[machine]
name    = Pentagon
family  = clone
hw      = Pentagon
memory  = 128
cpu.frq = 3500000

[video]
geometry = Pentagon

[storage]
disk = trdos

[rom]
rom0 = 128p-0.rom
rom1 = 128p-1.rom
rom2 = gluck.rom
rom3 = trdos504t.rom
gs   = gs105b.rom

[rom.trdos503]
name = TR-DOS 5.03
rom3 = trdos.rom
