[machine]
name    = ZXM-Phoenix
family  = clone
hw      = Phoenix
memory  = 2048
cpu.frq = 3500000

[video]
geometry = ULA.Pentagon

[sound]
psg.type  = ym
soundrive = covox

[storage]
disk = trdos

[input]
mouse       = yes
joy.buttons = yes

[rom]
rom0 = phoenix.rom
gs   = gs105b.rom
