[machine]
name    = Profi
family  = clone
hw      = Profi
memory  = 1024
cpu.frq = 3500000

[video]
geometry = ULA.Profi

[sound]
psg.type   = ym
psg.frq    = 1.75
psg.stereo = acb
soundrive  = covox

[storage]
disk = trdos
ide  = profi

[input]
mouse       = yes
joy.buttons = yes

[rom]
rom0 = profi.rom
gs   = gs105b.rom
