[machine]
name      = ZS Scorpion 256
family    = clone
hw        = Scorpion
memory    = 256
cpu.frq   = 3500000
scrp.wait = yes

[video]
geometry  = ULA.Scorpion
4t-border = yes

[sound]
psg.type  = ym
soundrive = covox

[storage]
disk = trdos
ide  = smuc

[input]
mouse       = yes
joy.buttons = yes

[rom]
rom0 = 256s-0.rom
rom1 = 256s-1.rom
rom2 = 256s-2.rom
rom3 = 256s-3.rom
gs   = gs105b.rom
