[machine]
name    = ZX Spectrum 48K
family  = sinclair
hw      = ZX48
memory  = 64
cpu.frq = 3500000
contio  = yes
contmem = yes
reset   = basic48

[video]
geometry    = ZX 48K
contPattern = 1
earlyTiming = yes
4t-border   = yes

[sound]
psg.count = 0

[rom]
rom0 = 48.rom
