[machine]
name    = ZX Spectrum 48K + TR-DOS
inherit = zx48

# a Melodik or a Fuller Box, which is how these machines were used
[sound]
psg.count = 1

[storage]
disk = trdos

[input]
mouse       = yes
joy.buttons = yes

[rom]
rom1 = trdos.rom
