[machine]
name    = ZX Spectrum +2A
family  = sinclair
hw      = Plus2A
memory  = 128
cpu.frq = 3546900
contmem = yes

[video]
geometry    = ULA.Plus3
contPattern = 2
earlyTiming = yes
4t-border   = yes

[sound]
psg.frq    = 1.773447
psg.stereo = mono

[rom]
rom0 = plus3-0.rom
rom1 = plus3-1.rom
rom2 = plus3-2.rom
rom3 = plus3-3.rom
