[GENERAL]

startdefault = no
savepaths = yes
fdcturbo = yes
addboot = yes
exit.confirm = no
port = 30000
winpos = -1,-1
flpinterleave = 1
style =

[BOOKMARKS]


[PROFILES]

ZX Spectrum 48K = ZX Spectrum 48K.conf
ZX Spectrum 48K + TR-DOS = ZX Spectrum 48K + TR-DOS.conf
ZX Spectrum 128K = ZX Spectrum 128K.conf
ZX Spectrum 128K + TR-DOS = ZX Spectrum 128K + TR-DOS.conf
ZX Spectrum +2 = ZX Spectrum +2.conf
ZX Spectrum +2A = ZX Spectrum +2A.conf
ZX Spectrum +3 = ZX Spectrum +3.conf
Pentagon 128 = Pentagon 128.conf
Pentagon 512 = Pentagon 512.conf
Pentagon 1024 SL = Pentagon 1024 SL.conf
Scorpion ZS 256 = Scorpion ZS 256.conf
Profi = Profi.conf
ATM Turbo 2+ = ATM Turbo 2+.conf
ZXM-Phoenix = ZXM-Phoenix.conf
ZX Evo (BaseConf) = ZX Evo (BaseConf).conf
ZX Evo (TSConf) = ZX Evo (TSConf).conf
current = ZX Spectrum 128K + TR-DOS

[VIDEO]

layout = ATM Turbo 2+:448:312:64:56:64:16:64:8:32:256:192
layout = Pentagon:448:320:72:64:64:16:72:0:1:256:192
layout = Profi:448:312:64:56:64:16:64:72:64:256:192
layout = Scorpion:448:312:48:48:80:24:72:8:128:256:192
layout = TSConf:448:320:52:48:88:32:64:0:0:256:192
layout = ZX +2A/+3:456:311:64:48:64:16:72:1:128:256:192
layout = ZX 128K:456:311:64:48:64:16:72:1:120:256:192
layout = ZX 48K:448:312:64:56:64:16:64:8:120:256:192
scrDir =
scrFormat = png
scrCount = 50
scrInterval = 1
scrNoLeds = yes
scrNoBord = no
fullscreen = no
keepratio = yes
lowlatency = yes
scale = 2
greyscale = no
bordersize = 100
noflick = 0
noflick.mode = 0
noflick.gamma = 2.200000
shader = tvline-nocurve-light.txt

[ROMSETS]

name = ATM Turbo 2+
rom = atm2.rom:0:0:0
gs = gs105b.rom
font = sgen.rom

name = Pentagon 128
rom = 128p-0.rom:0:16:0
rom = 128p-1.rom:0:16:16
rom = gluck.rom:0:16:32
rom = trdos504t.rom:0:16:48
gs = gs105b.rom

name = Pentagon 128 (TR-DOS 5.03)
rom = 128p-0.rom:0:16:0
rom = 128p-1.rom:0:16:16
rom = gluck.rom:0:16:32
rom = trdos.rom:0:16:48
gs = gs105b.rom

name = Profi
rom = profi.rom:0:0:0
gs = gs105b.rom

name = Scorpion ZS 256
rom = 256s-0.rom:0:16:0
rom = 256s-1.rom:0:16:16
rom = 256s-2.rom:0:16:32
rom = 256s-3.rom:0:16:48
gs = gs105b.rom

name = Scorpion ZS 256 (ProfROM 3.9f)
rom = prof39f.rom:0:0:0
gs = gs105b.rom

name = ZX Evo (BaseConf)
rom = zxevo-fe.rom:0:0:0
gs = gs105b.rom
font = sgen.rom

name = ZX Evo (TSConf)
rom = tsconf.rom:0:0:0
gs = gs105b.rom
font = sgen.rom

name = ZX Spectrum +2
rom = plus2-0.rom:0:16:0
rom = plus2-1.rom:0:16:16

name = ZX Spectrum +2A/+3 (v4.0)
rom = plus3-0.rom:0:16:0
rom = plus3-1.rom:0:16:16
rom = plus3-2.rom:0:16:32
rom = plus3-3.rom:0:16:48

name = ZX Spectrum +3 (v4.1)
rom = plus3-41.rom:0:0:0

name = ZX Spectrum 128K
rom = 128-0.rom:0:16:0
rom = 128-1.rom:0:16:16
gs = gs105b.rom

name = ZX Spectrum 128K + TR-DOS
rom = 128-0.rom:0:16:0
rom = 128-1.rom:0:16:16
rom = trdos.rom:0:16:48
gs = gs105b.rom

name = ZX Spectrum 48K
rom = 48.rom:0:16:0

name = ZX Spectrum 48K + TR-DOS
rom = 48.rom:0:16:0
rom = trdos.rom:0:16:16

name = ZXM-Phoenix
rom = phoenix.rom:0:0:0
gs = gs105b.rom

[SOUND]

enabled = yes
soundsys = SDL
rate = 48000
volume.master = 100
volume.beep = 100
volume.tape = 80
volume.ay = 40
volume.gs = 100
volume.sdrv = 100
volume.saa = 100

[TAPE]

autoplay = yes
fast = yes

[INPUT]

gamepad =
deadzone = 8192
gamepad2 =
deadzone2 = 8192

[LEDS]

mouse = yes
joystick = yes
keyscan = yes
tape = yes
disk = yes
message = yes
fps = no
halt = yes

[DEBUGA]

dbsize = 8
dwsize = 4
dmsize = 32
scr.zoom = 1
window = -1:-1:-1:-1

[PALETTE]

dbg.header.txt = #ffffff

[KEYS]

