[MACHINE]

current = Spectrum +3
memory = 128
cpu.type = Z80
cpu.frq = 3546900
frq.mul = 1.000000
scrp.wait = no
contio = yes
contmem = yes

[ROMSET]

current = ZX Spectrum +2A/+3 (v4.0)
reset = basic128

[VIDEO]

geometry = ZX +2A/+3
4t-border = yes
ULAplus = no
contPattern = 2
earlyTiming = yes
DDpal = no
palette = xpeccy.txt

[SOUND]

psg.count = 1
psg.type = 1
psg.frq = 1.773447
psg.stereo = 2
psg.mix = 25
gs = no
gs.reset = yes
gs.stereo = 1
soundrive_type = 0
saa = no

[TAPE]

speed = 100

[DISK]

type = 2

[INPUT]

mouse = yes
mouse.wheel = no
mouse.swapButtons = no
mouse.sensitivity = 1.000000
joy.extbuttons = yes
gamepad.map = kempston.pad

[IDE]

iface = 0
master.type = 0
slave.type = 0
