#include <sys/stat.h>
#include <sys/types.h>
#include <fstream>
#include <stdio.h>

#include <QtCore>

#include "xcore.h"
#include "vscalers.h"
#include "../xgui/xgui.h"
#include "sound.h"
#include "version.h"		// generated by CMake

#include "log.h"
#include "filemachine.h"

#ifdef _WIN32
	#include <windows.h>
	#include <direct.h>
#endif

enum {
	SECT_NONE = 0,
	SECT_BOOKMARK,
	SECT_PROFILES,
	SECT_VIDEO,
	SECT_ROMSETS,
	SECT_SOUND,
	SECT_TOOLS,
	SECT_GENERAL,
	SECT_TAPE,
	SECT_LEDS,
	SECT_INPUT,
	SECT_DEBUGA,
	SECT_PALETTE,
	SECT_KEYS,
	SECT_LOG,
	SECT_MACOVER,
	SECT_MEDIA,
	SECT_FILETYPES,
};

std::map<std::string, int> shotFormat;
xConfig conf;

void conf_init(char* wpath, char* confdir) {
	conf.scrShot.dir = std::string(getenv(ENVHOME));
	conf.port = 30000;
#if defined(__linux) || defined(__APPLE__) || defined(__BSD)
	if (confdir == NULL) {
		// own directory, not the one upstream Xpeccy uses (~/.config/samstyle/xpeccy):
		// both may be installed side by side, they must not share settings
		const char* xdg = getenv("XDG_CONFIG_HOME");
		if (xdg && *xdg) {
			conf.path.confDir = std::string(xdg);
		} else {
			conf.path.confDir = std::string(getenv(ENVHOME)) + "/.config";
		}
		mkdir(conf.path.confDir.c_str(), 0777);
		conf.path.confDir += "/xpeccy-plus";
	} else {
		conf.path.confDir = std::string(confdir);
	}
	mkdir(conf.path.confDir.c_str(), 0777);
	conf.path.romDir = conf.path.confDir + "/roms";
	mkdir(conf.path.romDir.c_str() ,0777);
	conf.path.prfDir = conf.path.confDir + "/profiles";
	conf.path.nvDir = conf.path.confDir + "/nvram";
	mkdir(conf.path.nvDir.c_str() ,0777);
	mkdir((conf.path.confDir + "/shaders").c_str() ,0777);
	conf.path.palDir = conf.path.confDir + "/palettes";
	mkdir(conf.path.palDir.c_str() ,0777);
	conf.path.plgDir = conf.path.confDir + "/plugins";
	mkdir((conf.path.confDir + "/styles").c_str() ,0777);
	conf.path.confFile = conf.path.confDir + "/config.conf";
	conf.path.boot = conf.path.confDir + "/boot.$B";
#elif defined(__WIN32)
	if (confdir == NULL) {
		conf.path.confDir = std::string(wpath);
		size_t pos = conf.path.confDir.find_last_of(SLSH);
		if (pos != std::string::npos) {
			conf.path.confDir = conf.path.confDir.substr(0, pos);
		}
		conf.path.confDir += "\\config";
	} else {
		conf.path.confDir = std::string(confdir);
	}
	conf.path.romDir = conf.path.confDir + "\\roms";
	conf.path.prfDir = conf.path.confDir + "\\profiles";
	conf.path.nvDir = conf.path.confDir + "\\nvram";
	conf.path.palDir = conf.path.confDir + "\\palettes";
	conf.path.plgDir = conf.path.confDir + "\\plugins";
	conf.path.confFile = conf.path.confDir + "\\config.conf";
	conf.path.boot = conf.path.confDir + "\\boot.$B";
	mkdir(conf.path.confDir.c_str());
	mkdir(conf.path.romDir.c_str());
	mkdir(conf.path.nvDir.c_str());
	mkdir((conf.path.confDir + "\\shaders").c_str());
	mkdir(conf.path.palDir.c_str());
	mkdir((conf.path.confDir + "\\styles").c_str());
#endif
	conf.scrShot.format = "png";
	conf.running = 0;
	conf.boot = 1;
	conf.autorun = 1;
	conf.tape.rewind = 1;
	conf.emu.pause = 0;
	conf.emu.fast = 0;
	conf.gpctrl = new xGamepadController;

	init_sin_tab();
}

void saveConfig() {
	FILE* cfile = fopen(conf.path.confFile.c_str(), "wb");
	if (!cfile) {
		shitHappens("Can't write main config");
		throw(0);
	}

	fprintf(cfile,"[GENERAL]\n\n");
	fprintf(cfile, "schema = 2\n");
	fprintf(cfile, "machine = %s\n", conf.macId.c_str());
	fprintf(cfile, "lastdir = %s\n", conf.lastDir.c_str());
	fprintf(cfile, "savepaths = %s\n", YESNO(conf.storePaths));
	fprintf(cfile, "fdcturbo = %s\n", YESNO(fdcFlag & FDC_FAST));
	fprintf(cfile, "addboot = %s\n", YESNO(conf.boot));
	fprintf(cfile, "autorun = %s\n", YESNO(conf.autorun));
	fprintf(cfile, "exit.confirm = %s\n",YESNO(conf.confexit));
	fprintf(cfile, "port = %i\n", conf.port);
	fprintf(cfile, "winpos = %i,%i\n",conf.xpos,conf.ypos);
	fprintf(cfile, "keywin.dock = %s\n", YESNO(conf.keywin.dock));
	fprintf(cfile, "keywin.width = %i\n", conf.keywin.width);
	fprintf(cfile, "flpinterleave = %i\n", flp_get_interleave());
	fprintf(cfile, "style = %s\n", conf.style.c_str());

	fprintf(cfile, "\n[BOOKMARKS]\n\n");
	foreach(xBookmark bkm, conf.bookmarkList) {
		fprintf(cfile, "%s = %s\n", bkm.name.c_str(), bkm.path.c_str());
	}

	fprintf(cfile, "\n[VIDEO]\n\n");
	fprintf(cfile, "palette = %s\n", conf.palette.c_str());
	fprintf(cfile, "scrDir = %s\n", conf.scrShot.dir.c_str());
	fprintf(cfile, "scrFormat = %s\n", conf.scrShot.format.c_str());
	fprintf(cfile, "scrCount = %i\n", conf.scrShot.count);
	fprintf(cfile, "scrInterval = %i\n", conf.scrShot.interval);
	fprintf(cfile, "scrNoLeds = %s\n", YESNO(conf.scrShot.noLeds));
	fprintf(cfile, "scrNoBord = %s\n", YESNO(conf.scrShot.noBorder));
	fprintf(cfile, "fullscreen = %s\n", YESNO(conf.vid.fullScreen));
	fprintf(cfile, "keepratio = %s\n", YESNO(conf.vid.keepRatio));
	fprintf(cfile, "lowlatency = %s\n", YESNO(conf.vid.lowLatency));
	// kept beside lowlatency: the two are one page in the options, and moving
	// a key between sections later would orphan everyone's setting
	fprintf(cfile, "runahead = %i\n", conf.emu.runahead);
	fprintf(cfile, "scale = %i\n", conf.vid.scale);
	fprintf(cfile, "greyscale = %s\n", YESNO(greyScale));
//	fprintf(cfile, "scanlines = %s\n", YESNO(scanlines));
	fprintf(cfile, "border = %s\n", brd_mode_name(conf.vid.border));
	fprintf(cfile, "noflick = %i\n", noflic);
	fprintf(cfile, "noflick.mode = %i\n", noflicMode);
	fprintf(cfile, "noflick.gamma = %f\n", noflicGamma);
	fprintf(cfile, "shader = %s\n", conf.vid.shader.c_str());
	fprintf(cfile, "\n[SOUND]\n\n");
	fprintf(cfile, "enabled = %s\n", YESNO(conf.snd.enabled));
	fprintf(cfile, "soundsys = %s\n", sndOutput->name);
	fprintf(cfile, "rate = %i\n", conf.snd.rate);
	fprintf(cfile, "rate_auto = %s\n", YESNO(conf.snd.rateauto));
	fprintf(cfile, "latency = %i\n", conf.snd.latency);
	fprintf(cfile, "latency_auto = %s\n", YESNO(conf.snd.latauto));
	fprintf(cfile, "volume.master = %i\n", conf.snd.vol.master);
	fprintf(cfile, "volume.beep = %i\n", conf.snd.vol.beep);
	fprintf(cfile, "volume.tape = %i\n", conf.snd.vol.tape);
	fprintf(cfile, "volume.ay = %i\n", conf.snd.vol.ay);
	fprintf(cfile, "volume.gs = %i\n", conf.snd.vol.gs);
	fprintf(cfile, "volume.sdrv = %i\n", conf.snd.vol.sdrv);
	fprintf(cfile, "volume.saa = %i\n", conf.snd.vol.saa);

	fprintf(cfile, "psg.frq = %f\n", conf.zx->ts->chipA->frq);
	fprintf(cfile, "psg.stereo = %i\n", conf.zx->ts->chipA->stereo);
	fprintf(cfile, "psg.separation = %i\n", conf.zx->ts->chipA->sep);
	fprintf(cfile, "gs.reset = %s\n", YESNO(conf.zx->gs->reset));
	fprintf(cfile, "gs.stereo = %i\n", conf.zx->gs->stereo);

	fprintf(cfile, "\n[TAPE]\n\n");
	fprintf(cfile, "speed = %i\n", conf.zx->tape->speed);
	fprintf(cfile, "autoplay = %s\n", YESNO(conf.tape.autostart));
	fprintf(cfile, "fast = %s\n", YESNO(conf.tape.fast));
	fprintf(cfile, "rewind = %s\n", YESNO(conf.tape.rewind));

	fm_save(cfile);

	fprintf(cfile, "\n[INPUT]\n\n");
	fprintf(cfile, "mouse.swapButtons = %s\n", YESNO(conf.zx->mouse->swapButtons));
	fprintf(cfile, "mouse.sensitivity = %f\n", conf.zx->mouse->sensitivity);
	fprintf(cfile, "mouse.pctype = %i\n", conf.zx->mouse->pcmode);
	fprintf(cfile, "keymap = %s\n", conf.kmapName.c_str());
	fprintf(cfile, "gamepad.map = %s\n", conf.jmapNameA.c_str());
	fprintf(cfile, "gamepad2.map = %s\n", conf.jmapNameB.c_str());
	fprintf(cfile, "frq.mul = %f\n", conf.zx->frqMul);
	// What each slot remembers, whether or not that pad is plugged in now.
	// A sleeping wireless pad must read the same here as an awake one.
	fprintf(cfile, "gamepad = %s\n", conf.gpctrl->gpada->padId().toConfig().toUtf8().data());
	fprintf(cfile, "deadzone = %i\n", conf.gpctrl->gpada->deadZone());
	fprintf(cfile, "gamepad2 = %s\n", conf.gpctrl->gpadb->padId().toConfig().toUtf8().data());
	fprintf(cfile, "deadzone2 = %i\n", conf.gpctrl->gpadb->deadZone());

	fprintf(cfile, "\n[LEDS]\n\n");
	fprintf(cfile, "mouse = %s\n", YESNO(conf.led.mouse));
	fprintf(cfile, "joystick = %s\n", YESNO(conf.led.joy));
	fprintf(cfile, "keyscan = %s\n", YESNO(conf.led.keys));
	fprintf(cfile, "tape = %s\n", YESNO(conf.led.tape));
	fprintf(cfile, "disk = %s\n", YESNO(conf.led.disk));
	fprintf(cfile, "message = %s\n", YESNO(conf.led.message));
	fprintf(cfile, "fps = %s\n", YESNO(conf.led.fps));
	fprintf(cfile, "halt = %s\n", YESNO(conf.led.halt));

	fprintf(cfile, "\n[DEBUGA]\n\n");
	fprintf(cfile, "dbsize = %i\n", conf.dbg.dbsize);
	fprintf(cfile, "dwsize = %i\n", conf.dbg.dwsize);
	fprintf(cfile, "dmsize = %i\n", conf.dbg.dmsize);
	fprintf(cfile, "stack.offset = %i\n", conf.dbg.stackofs);
	fprintf(cfile, "scr.zoom = %i\n", conf.dbg.scrzoom);
	fprintf(cfile, "regs.layout = %i\n", conf.dbg.reglayout);
	fprintf(cfile, "regs.split = %s\n", YESNO(conf.dbg.regsplit));
	fprintf(cfile, "dim.address = %s\n", YESNO(conf.dbg.dimadr));
	fprintf(cfile, "dim.opcodes = %s\n", YESNO(conf.dbg.dimops));
	fprintf(cfile, "syntax.colors = %s\n", YESNO(conf.dbg.synhl));
	fprintf(cfile, "block.separator = %s\n", YESNO(conf.dbg.blocksep));
	fprintf(cfile, "show.memmap = %s\n", YESNO(conf.dbg.showmmap));
	fprintf(cfile, "show.ports = %s\n", YESNO(conf.dbg.showports));
	fprintf(cfile, "show.signals = %s\n", YESNO(conf.dbg.showsig));
	fprintf(cfile, "show.ray = %s\n", YESNO(conf.dbg.showray));
	fprintf(cfile, "show.frame = %s\n", YESNO(conf.dbg.showfrm));
	fprintf(cfile, "font = %s\n", conf.dbg.font.toString().toUtf8().data());
	fprintf(cfile, "window = %i:%i:%i:%i\n",conf.dbg.pos.x(),conf.dbg.pos.y(),conf.dbg.siz.width(),conf.dbg.siz.height());
	QStringList pts = getWatchPorts(conf.zx, 0);
	if (!pts.isEmpty())
		fprintf(cfile, "ports = %s\n", pts.join(",").toLatin1().data());

	fprintf(cfile, "\n[PALETTE]\n\n");
	QStringList lst = conf.pal.keys();
	QString nam;
	QColor col;
	foreach(nam, lst) {
		col = conf.pal[nam];
		if (col.isValid())
			fprintf(cfile, "%s = %s\n", nam.toLocal8Bit().data(), col.name().toLocal8Bit().data());
	}

	fprintf(cfile, "\n[LOG]\n\n");
	log_save(cfile);

	fprintf(cfile, "\n[KEYS]\n\n");
	xShortcut* tab = shortcut_tab();
	int i = 0;
	while (tab[i].id > 0) {
		fprintf(cfile, "%s = %s\n", tab[i].name, tab[i].seq.toString().toLocal8Bit().data());
		i++;
	}

	xm_save(cfile);
	xm_save_media(cfile);
	fclose(cfile);
}

// The debugger's own colours. One table, three users: the values set at
// startup, the default a right click in the palette editor puts back, and
// what a switch to "System" restores.

static const struct { const char* name; const char* color; } dbgPalTab[] = {
	{"dbg.header.bg", "#4f96ed"},	{"dbg.header.txt", "#ffffff"},	// as shipped in config.conf
	{"dbg.pc.bg", "#2ccc00"},	{"dbg.pc.txt", "#000000"},
	{"dbg.sel.bg", "#98ff98"},	{"dbg.sel.txt", "#000000"},
	{"dbg.changed.bg", "#ffcece"},	{"dbg.changed.txt", "#000000"},
	{"dbg.brk.txt", "#ef2929"},
	{"dbg.disk.id.bg", "#dcdcff"},	{"dbg.disk.id.txt", "#000000"},	// track dump
	{"dbg.disk.data.bg", "#dcffdc"},{"dbg.disk.data.txt", "#000000"},
	{"dbg.disk.crc.bg", "#ffdcff"},	{"dbg.disk.crc.txt", "#000000"},
	{"dbg.asm.const.txt", "#762d9b"},				// constants in the listing
	{NULL, NULL}
};

void dbgPaletteDefaults() {
	for (int i = 0; dbgPalTab[i].name; i++)
		conf.pal[dbgPalTab[i].name] = QColor(dbgPalTab[i].color);
}

const char* dbgPaletteDefault(const char* name) {
	for (int i = 0; dbgPalTab[i].name; i++)
		if (!strcmp(name, dbgPalTab[i].name))
			return dbgPalTab[i].color;
	return "";
}

// A style sheet may bring debugger colours along, in a .pal file next to it
// (Dark.qss -> Dark.pal), same 'name = #rrggbb' lines as the [PALETTE] section.
// Only the names the file mentions are touched, the rest is left as it is.
// Called when the style changes, never on startup: whatever the user edited
// afterwards is in config.conf and must win.

bool loadStylePalette(const std::string& style) {
	if (style.empty()) return false;
	QFile file(xres_path("styles",
		QFileInfo(QString::fromLocal8Bit(style.c_str())).completeBaseName() + ".pal"));
	if (!file.open(QFile::ReadOnly | QFile::Text)) return false;
	QTextStream strm(&file);
	while (!strm.atEnd()) {
		QString line = strm.readLine();
		int pos = line.indexOf(';');			// comment
		if (pos >= 0) line = line.left(pos);
		pos = line.indexOf('=');
		if (pos < 0) continue;
		QString nam = line.left(pos).trimmed();
		QColor col(line.mid(pos + 1).trimmed());
		if (!nam.isEmpty() && col.isValid())
			conf.pal[nam] = col;
	}
	file.close();
	return true;
}

void copyFile(const char* src, const char* dst) {
	QFile fle(QString::fromLocal8Bit(src));
	fle.open(QFile::ReadOnly);
	QByteArray fdata = fle.readAll();
	fle.close();
	fle.setFileName(QString::fromLocal8Bit(dst));
	if (fle.open(QFile::WriteOnly)) {
		fle.write(fdata);
		fle.close();
	}
}

// where the installed machine configuration (roms, profiles, palettes, shaders)
// lives, relative to the binary. Windows keeps it next to the executable, which
// is the config directory itself, so there is nothing to copy there.

static QString sysConfigDir() {
#if defined(__APPLE__)
	// inside the bundle: Contents/MacOS/<binary> -> Contents/Resources/config
	return QCoreApplication::applicationDirPath() + "/../Resources/config";
#elif defined(__linux) || defined(__BSD)
	// works for /usr/bin as well as for an AppImage, where the whole prefix
	// sits under $APPDIR
	return QCoreApplication::applicationDirPath() + "/../share/" XPKGNAME "/config";
#else
	return QString();
#endif
}

// add to the config directory whatever the installed configuration has and it
// lacks, so files an update brings along show up. Files already there are left
// alone, edits included.

static void seedConfigDir(const QString& src) {
	QDir sdir(src);
	if (src.isEmpty() || !sdir.exists()) return;
	QString dst = QString::fromLocal8Bit(conf.path.confDir.c_str());
	QDirIterator it(src, QDir::Files | QDir::Dirs | QDir::NoDotAndDotDot, QDirIterator::Subdirectories);
	int cnt = 0;
	while (it.hasNext()) {
		QString path = it.next();
		QString rel = sdir.relativeFilePath(path);
		if (it.fileInfo().isDir()) {
			QDir().mkpath(dst + "/" + rel);
		} else if (!QFile::exists(dst + "/" + rel)) {
			QDir().mkpath(QFileInfo(dst + "/" + rel).path());
			copyFile(path.toLocal8Bit().data(), (dst + "/" + rel).toLocal8Bit().data());
			cnt++;
		}
	}
	if (cnt) xlog(XLG_CONF, XLL_INFO, "%i files copied from %s", cnt, src.toLocal8Bit().data());
}

// emulator config

// THE CONFIGURATION AS ONE FILE
//
// Everything a setup is made of, in one text file: the settings, the screen
// layouts and the machines of the user's own. Plain text on purpose - it is
// meant to be read, diffed and pasted into a bug report. Roms, palettes,
// shaders, styles and keymaps are not in it: those are files a person put
// there, not settings, and the ones that ship are in the binary anyway.
//
// A line of the form [[<name>]] at the left margin starts a file; everything
// up to the next one is its content.

#define	XCONF_MARK	"[["

// the settings themselves; the machines come from the module that owns them

static const char* xconfFile[] = {"config.conf", "layouts.conf", NULL};

static QString xconf_dir() {
	return QString::fromLocal8Bit(conf.path.confDir.c_str());
}

static QStringList xconf_files() {
	QStringList res;
	for (int i = 0; xconfFile[i]; i++)
		res << xconfFile[i];
	return res + xm_user_files();
}

// The caller commits what it has first: this writes the files as they stand.

bool xconf_export(const QString& path) {
	QFile out(path);
	if (!out.open(QFile::WriteOnly)) {
		xlog(XLG_CONF, XLL_ERROR, "can't write %s", path.toLocal8Bit().data());
		return false;
	}
	QString head = QString("# " XPRODUCT " configuration, version " XVERSION "\n"
		"# Import it in Options - Xpeccy+ - General.\n");
	out.write(head.toLocal8Bit());
	QString base = xconf_dir();
	foreach(QString nam, xconf_files()) {
		QFile in(base + SLASH + nam);
		if (!in.open(QFile::ReadOnly)) continue;	// nothing of that kind here
		out.write(QString("\n" XCONF_MARK "%1]]\n").arg(nam).toLocal8Bit());
		out.write(in.readAll());
		in.close();
	}
	out.close();
	xlog(XLG_CONF, XLL_INFO, "configuration exported to %s", path.toLocal8Bit().data());
	return true;
}

// the files of the config directory this one is allowed to write over. Not
// the list above: a machine that is not here yet is exactly what an imported
// file is expected to bring

static bool xconf_may_write(const QString& nam) {
	if (nam.contains("..") || nam.contains(':')) return false;
	for (int i = 0; xconfFile[i]; i++) {
		if (nam == xconfFile[i]) return true;
	}
	return xm_is_user_file(nam);
}

bool xconf_import(const QString& path) {
	QFile in(path);
	if (!in.open(QFile::ReadOnly | QFile::Text)) {
		xlog(XLG_CONF, XLL_ERROR, "can't read %s", path.toLocal8Bit().data());
		return false;
	}
	QMap<QString, QByteArray> part;
	QString nam;
	while (!in.atEnd()) {
		QByteArray line = in.readLine();
		QString txt = QString::fromLocal8Bit(line).trimmed();
		if (txt.startsWith(XCONF_MARK) && txt.endsWith("]]")) {
			nam = txt.mid(2, txt.size() - 4);
			if (!xconf_may_write(nam)) {
				xlog(XLG_CONF, XLL_WARN, "not importing '%s'", nam.toLocal8Bit().data());
				nam.clear();
			} else {
				part[nam] = QByteArray();
			}
		} else if (!nam.isEmpty()) {
			part[nam] += line;
		}
	}
	in.close();
	if (part.isEmpty()) {
		xlog(XLG_CONF, XLL_ERROR, "%s holds no configuration", path.toLocal8Bit().data());
		return false;
	}
	QString base = xconf_dir();
	foreach(QString key, part.keys()) {
		QString dst = base + SLASH + key;
		QDir().mkpath(QFileInfo(dst).path());
		QFile f(dst);
		if (!f.open(QFile::WriteOnly)) {
			xlog(XLG_CONF, XLL_ERROR, "can't write %s", dst.toLocal8Bit().data());
			continue;
		}
		f.write(part.value(key));
		f.close();
	}
	xlog(XLG_CONF, XLL_INFO, "configuration imported from %s", path.toLocal8Bit().data());
	return reloadConfig();
}

// back to what the emulator ships with: the settings file and the layouts go,
// and the next read takes the defaults out of the binary. Machines of the
// user's own are content, not settings, and are left where they are.

bool xconf_reset() {
	for (int i = 0; xconfFile[i]; i++)
		QFile::remove(xconf_dir() + SLASH + xconfFile[i]);
	return reloadConfig();
}

// Reading the configuration again, into the machine and the windows that are
// already up. loadConfig() is written to be able to do this - it clears every
// list it fills and keeps conf.zx - and it throws when there is nothing to
// read at all, which here would take the whole emulator down with it.

bool reloadConfig() {
	// loadConfig() is startup: it re-opens the sound output and rescans the
	// gamepads as well as reading the files, and it does it under a machine
	// that is already running
	emu_lock();
	conf.emu.pause |= PR_EXTRA;
	try {
		loadConfig();
	} catch (...) {
		xlog(XLG_CONF, XLL_ERROR, "the configuration could not be read");
		conf.emu.pause &= ~PR_EXTRA;
		emu_unlock();
		return false;
	}
	conf.emu.pause &= ~PR_EXTRA;
	emu_unlock();
	return true;
}

void loadConfig() {
	std::string soutnam = "NULL";
	//printf("%s\n",conf.path.confFile);
	// on every start, not only on the first one: this is how a new file added
	// by an update reaches a config directory that already exists
	seedConfigDir(sysConfigDir());
	std::ifstream file(conf.path.confFile);
	char fname[FILENAME_MAX];
	if (!file.good()) {
		xlog(XLG_CONF, XLL_WARN, "main config is missing, copying the default files");
		// no file to copy from an install either: the defaults are in the
		// binary, and so are the roms the machine they name needs
		copyFile(":/res/fallback/config.conf", conf.path.confFile.c_str());
		static const char* seedRom[] = {"48.rom", "128-0.rom", "128-1.rom", NULL};
		for (int i = 0; seedRom[i]; i++) {
			snprintf(fname, sizeof(fname), "%s" SLASH "%s", conf.path.romDir.c_str(), seedRom[i]);
			copyFile((std::string(":/config/roms/") + seedRom[i]).c_str(), fname);
		}
		file.open(conf.path.confFile);
		if (!file.good()) {
			xlog(XLG_CONF, XLL_ERROR, "no main config at %s", conf.path.confFile.c_str());
			shitHappens("<b>Doh! Something going wrong</b>");
			throw(0);
		}
	}
	layouts_load_all();
	xm_load_all();
	xm_over_clear();
	if (!conf.zx) {
		conf.zx = compCreate();
		// what the machine says it is when software asks (ZX Evo does)
		comp_set_identity(conf.zx, XPRODUCT, XBUILD_YMD, XRELEASE_BUILD);
		compSetHardware(conf.zx, "Dummy");
	}
	conf.bookmarkList.clear();
	fm_clear();
	char buf[0x4000];
	QColor col;
	std::pair<std::string,std::string> spl;
	std::string line,pnam,pval;
	std::string pnm = "default";
	int section = SECT_NONE;
	int schema = 1;
	std::string macover;
	std::map<std::string, std::string> oldprf;
	std::vector<std::string> vect;
	std::vector<xRomset> rsListist;
	xRomset newrs;
	xRomFile rfile;
	size_t pos;
	std::string tms,fnam;
	int fprt;
	newrs.fntFile.clear();
	newrs.gsFile.clear();
	newrs.vBiosFile.clear();
	newrs.roms.clear();
	conf.pal.clear();
	shortcut_init();
	conf.xpos = -1;
	conf.ypos = -1;
	conf.keywin.dock = 0;
	conf.keywin.width = 0;
	conf.vid.border = VID_BRD_FULL;
	conf.vid.scale = 2;		// a config with no scale must not make a zero-size window
	conf.dbg.dbsize = 8;
	conf.dbg.dwsize = 4;
	conf.dbg.dmsize = 127;
	conf.dbg.stackofs = -2;
	conf.dbg.scrzoom = 1;
	conf.dbg.reglayout = DBG_REGS_AUTO;
	conf.dbg.regsplit = 1;
	conf.dbg.dimadr = 0;
	conf.dbg.dimops = 1;
	conf.dbg.synhl = 1;
	conf.dbg.blocksep = 1;
	conf.dbg.showmmap = 1;
	conf.dbg.showports = 1;
	conf.dbg.showsig = 1;
	conf.dbg.showray = 1;
	conf.dbg.showfrm = 1;
	conf.dbg.siz = QSize(960, 720);		// deBUGa default, until the user resizes it
	conf.dbg.font = QFont("DejaVu Sans Mono", 9);		// default, shipped in the resources
// init volumes
	conf.snd.vol.master = 100;
	conf.snd.vol.beep = 100;
	conf.snd.vol.tape = 100;
	conf.snd.vol.ay = 100;
	conf.snd.vol.gs = 100;
	conf.snd.vol.sdrv = 100;
	conf.snd.vol.saa = 100;
// init palette
	dbgPaletteDefaults();

	xArg arg;

	while (!file.eof()) {
		file.getline(buf,2048);
		line = std::string(buf);
		spl = splitline(line);
		pnam = spl.first;
		pval = spl.second;
		arg.b = str2bool(pval);
		arg.s = pval.c_str();
		arg.i = strtol(arg.s, NULL, 0);
		arg.d = strtod(arg.s, NULL);
		if (pnam.empty()) continue;		// a blank line, or one that is all comment
		// a line with nothing after the = is a value, not a section: an empty
		// value is how a rom bank is emptied and a setting is cleared
		if (pnam[0] == '[') {
			if (pnam=="[BOOKMARKS]") section = SECT_BOOKMARK;
			if (pnam=="[PROFILES]") section = SECT_PROFILES;
			if (pnam=="[MEDIA]") section = SECT_MEDIA;
			if (pnam.compare(0, 9, "[MACHINE.") == 0) {
				section = SECT_MACOVER;
				macover = pnam.substr(9, pnam.size() - 10);
			}
			if (pnam=="[VIDEO]") section = SECT_VIDEO;
			if (pnam=="[ROMSETS]") section = SECT_ROMSETS;
			if (pnam=="[SOUND]") section = SECT_SOUND;
			if (pnam=="[TOOLS]") section = SECT_TOOLS;
			if (pnam=="[GENERAL]") section = SECT_GENERAL;
			if (pnam=="[TAPE]") section = SECT_TAPE;
			if (pnam=="[LEDS]") section = SECT_LEDS;
			if (pnam=="[INPUT]") section = SECT_INPUT;
			if (pnam=="[DEBUGA]") section = SECT_DEBUGA;
			if (pnam=="[PALETTE]") section = SECT_PALETTE;
			if (pnam=="[KEYS]") section = SECT_KEYS;
			if (pnam=="[LOG]") section = SECT_LOG;
			if (pnam=="[FILETYPES]") section = SECT_FILETYPES;
		} else {
			switch (section) {
				case SECT_KEYS:
					set_shortcut_name(pnam.c_str(), QKeySequence(arg.s));
					break;
				case SECT_PALETTE:
					col = QColor(arg.s);
					if (col.isValid())
						conf.pal[QString(pnam.c_str())] = col;
					break;
				case SECT_DEBUGA:
					if (pnam == "dbsize") conf.dbg.dbsize = arg.i;
					if (pnam == "dwsize") conf.dbg.dwsize = arg.i;
					if (pnam == "dmsize") conf.dbg.dmsize = arg.i;
					if ((pnam == "stack.offset") && (arg.i >= -DBG_STACK_OFS) && (arg.i <= DBG_STACK_OFS))
						conf.dbg.stackofs = arg.i & ~1;
					if (pnam == "font") conf.dbg.font.fromString(QString(arg.s));
					if (pnam == "window") {
						vect = splitstr(pval,":");
						if (vect.size() < 4) {
							vect.insert(vect.begin(), "0");
							vect.insert(vect.begin(), "0");
						}
						if (vect.size() > 3) {
							fprt = atoi(vect[0].c_str()); if (fprt >= 0) conf.dbg.pos.setX(fprt);
							fprt = atoi(vect[1].c_str()); if (fprt >= 0) conf.dbg.pos.setY(fprt);
							fprt = atoi(vect[2].c_str()); if (fprt > 0) conf.dbg.siz.setWidth(fprt);
							fprt = atoi(vect[3].c_str()); if (fprt > 0) conf.dbg.siz.setHeight(fprt);
						}
					}
					if ((pnam == "scr.zoom") && (arg.i > 0) && (arg.i < 4))
						conf.dbg.scrzoom = arg.i;
					if (pnam == "ports") xm_defer(pnam, pval);
					if ((pnam == "regs.layout") && ((arg.i == DBG_REGS_AUTO) || (arg.i == DBG_REGS_1COL)
							|| (arg.i == DBG_REGS_2COL) || (arg.i == DBG_REGS_WIDE)))
						conf.dbg.reglayout = arg.i;
					if (pnam == "regs.split") conf.dbg.regsplit = arg.b;
					if (pnam == "dim.address") conf.dbg.dimadr = arg.b;
					if (pnam == "dim.opcodes") conf.dbg.dimops = arg.b;
					if (pnam == "syntax.colors") conf.dbg.synhl = arg.b;
					if (pnam == "block.separator") conf.dbg.blocksep = arg.b;
					if (pnam == "show.memmap") conf.dbg.showmmap = arg.b;
					if (pnam == "show.ports") conf.dbg.showports = arg.b;
					if (pnam == "show.signals") conf.dbg.showsig = arg.b;
					if (pnam == "show.ray") conf.dbg.showray = arg.b;
					if (pnam == "show.frame") conf.dbg.showfrm = arg.b;
					break;
				case SECT_LOG:
					log_load(pnam, arg.s, arg.b);
					break;
				case SECT_FILETYPES:
					fm_load(pnam, pval);
					break;
				case SECT_BOOKMARK:
					addBookmark(pnam, pval);
					break;
				case SECT_PROFILES:		// only a config written before schema 2 has this
					if (pnam == "current") {
						pnm = pval;
					} else {
						oldprf[pnam] = pval;
					}
					break;
				case SECT_MACOVER:
					xm_over_add(macover, pnam, pval);
					break;
				case SECT_MEDIA:
					xm_defer(pnam, pval);
					break;
				case SECT_INPUT:
					if (pnam=="keymap") conf.kmapName = pval;
					if (pnam=="gamepad.map") conf.jmapNameA = pval;
					if (pnam=="gamepad2.map") conf.jmapNameB = pval;
					// kbd.scantab and mouse.wheel belong to the machine now and are
					// not written here any more; an older config still sets them, once
					if ((pnam=="mouse.wheel") || (pnam=="mouse.swapButtons") || (pnam=="mouse.sensitivity")
						|| (pnam=="mouse.pctype") || (pnam=="frq.mul") || (pnam=="kbd.scantab"))
						xm_defer(pnam, pval);
					if (pnam=="deadzone") conf.gpctrl->gpada->setDeadZone(arg.i);
					if (pnam=="deadzone2") conf.gpctrl->gpadb->setDeadZone(arg.i);
					if (pnam=="gamepad") conf.gpctrl->gpada->setPadId(xPadId::fromConfig(arg.s));
					if (pnam=="gamepad2") conf.gpctrl->gpadb->setPadId(xPadId::fromConfig(arg.s));
					break;
				case SECT_VIDEO:
					// a config from before the layouts had a file of their own
					if (pnam=="layout") addLayoutString(pval);
					if (pnam=="palette") conf.palette = pval;
					if (pnam=="scrDir") conf.scrShot.dir = pval;
					if (pnam=="scrFormat") conf.scrShot.format = pval;
					if (pnam=="scrCount") conf.scrShot.count = arg.i;
					if (pnam=="scrInterval") conf.scrShot.interval = arg.i;
					if (pnam=="scrNoLeds") conf.scrShot.noLeds = arg.b;
					if (pnam=="scrNoBord") conf.scrShot.noBorder = arg.b;
					if (pnam=="fullscreen") conf.vid.fullScreen = arg.b;
					if (pnam=="keepratio") conf.vid.keepRatio = arg.b;
					if (pnam=="lowlatency") conf.vid.lowLatency = arg.b;
					if (pnam=="runahead") conf.emu.runahead = getRanged(arg.s, 0, 2);
					if (pnam=="border") conf.vid.border = brd_mode_id(arg.s);
					// before 2026.4 this was a percentage of the machine's own border
					if (pnam=="bordersize") conf.vid.border = brd_mode_pcnt(getRanged(arg.s, 0, 100));
					if (pnam=="doublesize") conf.vid.scale = arg.b ? 2 : 1;
					if (pnam=="scale") {
						conf.vid.scale = arg.i;
						if (conf.vid.scale < 1) conf.vid.scale = 1;
						if (conf.vid.scale > 6) conf.vid.scale = 6;
					}
					if (pnam=="noflic") noflic = arg.b ? 50 : 25;		// old parameter
					if (pnam=="noflick") noflic = getRanged(arg.s, 0, 50);	// new parameter
					if (pnam=="noflick.mode") noflicMode = arg.i;
					if (pnam=="noflick.gamma") {
						noflicGamma = arg.d;
						if (noflicGamma < 1) noflicGamma = 1;
						if (noflicGamma > 3) noflicGamma = 3;
					}
					if (pnam=="greyscale") vid_set_grey(arg.b);
					if (pnam=="shader") conf.vid.shader = pval;
					break;
				case SECT_ROMSETS:
					pos = pval.find_last_of(":");
					vect = splitstr(pval, ":");
					if (pos != std::string::npos) {
						fnam = std::string(pval,0,pos);
						tms = std::string(pval,pos+1);
						if (tms=="") {
							fprt = 0;
						} else {
							fprt = atoi(tms.c_str());
						}
					} else {
						fnam = pval;
						fprt = 0;
					}
					if (pnam=="name") {
						newrs.name = pval;
						rsListist.push_back(newrs);
					}
					if (rsListist.size() != 0) {
						if ((pnam == "rom") && (vect.size() > 0)) {
							while (vect.size() < 4) {
								vect.push_back("0");
							}
							rfile.name = vect[0];
							rfile.foffset = atoi(vect[1].c_str());
							rfile.fsize = atoi(vect[2].c_str());
							rfile.roffset = atoi(vect[3].c_str());
							rsListist.back().roms.push_back(rfile);
						} else if (pnam=="file") {
							rfile.name = fnam;
							rfile.foffset = 0;
							rfile.fsize = 0;
							rfile.roffset = 0;
							rsListist.back().roms.push_back(rfile);
						} else if ((pnam=="basic128") || (pnam=="0")) {
							rfile.name = fnam;
							rfile.foffset = fprt * 16;
							rfile.fsize = 16;
							rfile.roffset = 0;
							rsListist.back().roms.push_back(rfile);
						} else if ((pnam=="basic48") || (pnam=="1")) {
							rfile.name = fnam;
							rfile.foffset = fprt * 16;
							rfile.fsize = 16;
							rfile.roffset = 16;
							rsListist.back().roms.push_back(rfile);
						} else if ((pnam=="shadow") || (pnam=="2")) {
							rfile.name = fnam;
							rfile.foffset = fprt * 16;
							rfile.fsize = 16;
							rfile.roffset = 32;
							rsListist.back().roms.push_back(rfile);
						} else if ((pnam=="trdos") || (pnam=="3")) {
							rfile.name = fnam;
							rfile.foffset = fprt * 16;
							rfile.fsize = 16;
							rfile.roffset = 48;
							rsListist.back().roms.push_back(rfile);
						}
						if (pnam=="gs") rsListist.back().gsFile=fnam;
						if (pnam=="font") rsListist.back().fntFile=fnam;
						if (pnam=="vga") rsListist.back().vBiosFile=fnam;
						if (pnam=="snd") rsListist.back().sBiosFile=fnam;
					}
					break;
				case SECT_SOUND:
					if (pnam=="enabled") conf.snd.enabled = arg.b;
					if (pnam=="soundsys") soutnam = pval;
					// a config written by an older build can name a rate this
					// one no longer offers; sndInit's default stands instead
					if (pnam=="rate") {
						if (sndRateSupported(arg.i)) conf.snd.rate = arg.i;
						else xlog(XLG_SOUND, XLL_WARN, "rate %i is not offered any more, using %i Hz", arg.i, conf.snd.rate);
					}
					if (pnam=="rate_auto") conf.snd.rateauto = arg.b;
					if (pnam=="latency") conf.snd.latency = getRanged(arg.s, SND_LATENCY_MIN, SND_LATENCY_MAX);
					if (pnam=="latency_auto") conf.snd.latauto = arg.b;
					if (pnam=="volume.master") conf.snd.vol.master = getRanged(arg.s, 0, 100);
					if (pnam=="volume.beep") conf.snd.vol.beep = getRanged(arg.s, 0, 100);
					if (pnam=="volume.tape") conf.snd.vol.tape = getRanged(arg.s, 0, 100);
					if (pnam=="volume.ay") conf.snd.vol.ay = getRanged(arg.s, 0, 100);
					if (pnam=="volume.gs") conf.snd.vol.gs = getRanged(arg.s, 0, 100);
					if (pnam=="volume.sdrv") conf.snd.vol.sdrv = getRanged(arg.s, 0, 100);
					if (pnam=="volume.saa") conf.snd.vol.saa = getRanged(arg.s, 0, 100);
					if ((pnam=="psg.frq") || (pnam=="psg.stereo") || (pnam=="psg.separation")
						|| (pnam=="gs.reset") || (pnam=="gs.stereo")) xm_defer(pnam, pval);
					break;
				case SECT_TOOLS:
					break;
				case SECT_GENERAL:
					if (pnam=="schema") schema = arg.i;
					if (pnam=="machine") conf.macId = pval;
					if (pnam=="lastdir") conf.lastDir = pval;
					if (pnam=="savepaths") conf.storePaths = arg.b;
					if (pnam == "fdcturbo") setFlagBit(arg.b, &fdcFlag, FDC_FAST);
					if (pnam == "port") conf.port = arg.i & 0xffff;
					if (pnam == "winpos") {
						vect = splitstr(pval, ",");
						if (vect.size() > 1) {
							conf.xpos = strtol(vect[0].c_str(), NULL, 10);
							conf.ypos = strtol(vect[1].c_str(), NULL, 10);
						}
					}
					if (pnam == "keywin.dock") conf.keywin.dock = arg.b;
					if (pnam == "keywin.width") conf.keywin.width = arg.i;
					if (pnam == "addboot") conf.boot = arg.b;
					if (pnam == "autorun") conf.autorun = arg.b;
					if (pnam == "exit.confirm") conf.confexit = arg.b;
					if (pnam == "flpinterleave") flp_set_interleave(arg.i);
					if (pnam == "style") conf.style = std::string(arg.s);
					break;
				case SECT_TAPE:
					if (pnam=="autoplay") conf.tape.autostart = arg.b;
					if (pnam=="fast") conf.tape.fast = arg.b;
					if (pnam=="rewind") conf.tape.rewind = arg.b;
					if (pnam=="speed") xm_defer("tape.speed", pval);
					break;
				case SECT_LEDS:
					if (pnam=="mouse") conf.led.mouse = arg.b;
					if (pnam=="joystick") conf.led.joy = arg.b;
					if (pnam=="keyscan") conf.led.keys = arg.b;
					if (pnam=="tape") conf.led.tape = arg.b;
					if (pnam=="disk") conf.led.disk = arg.b;
					if (pnam=="message") conf.led.message = arg.b;
					if (pnam=="fps") conf.led.fps = arg.b;
					if (pnam=="halt") conf.led.halt = arg.b;
					break;
			}
		}
	}
	padLoadControllerDb();		// before the pads open, it decides their layout
	conf.gpctrl->rescan();
	foreach(xRomset rs, rsListist) addRomset(rs);
//	prfLoadAll();
	setOutput(soutnam.c_str());
	bool ok = false;
	if (schema < 2) {			// a config from before the machines: bring it across
		std::string file = oldprf.count(pnm) ? oldprf[pnm] : "xpeccy.conf";
		ok = xm_migrate(pnm.empty() ? std::string("default") : pnm, file);
	} else {
		ok = xm_set(conf.macId);
	}
	if (!ok) {
		xlog(XLG_CONF, XLL_WARN, "no machine to start, taking the first one");
		if (xm_list().isEmpty() || !xm_set(xm_list().first().id)) {
			xlog(XLG_CONF, XLL_ERROR, "there are no machines at all");
			throw(0);
		}
	}
	xm_finish_load();
	conf.gpctrl->gpada->loadMap(conf.jmapNameA);
	conf.gpctrl->gpadb->loadMap(conf.jmapNameB);
	loadKeys();
	// this must be after setCurrentProfile
	vid_set_zoom(conf.vid.scale);
	vid_set_fullscreen(conf.vid.fullScreen);
	vid_set_ratio(conf.vid.keepRatio);
}
