#include "log.h"
#include "xcore.h"
#include "pacing.h"
#include "version.h"		// generated by CMake

#include <QCoreApplication>
#include <QDateTime>
#include <QDir>
#include <QFileInfo>
#include <QGuiApplication>
#include <QScreen>
#include <QSysInfo>
#include <QStringList>

#include <SDL.h>
#ifdef HAVEZLIB
#include <zlib.h>
#endif
#ifdef _WIN32
#include <windows.h>
#endif
#include <stdlib.h>
#include <string.h>

// What the command line asked for, over the top of conf.log. Kept apart so it
// is never written back: a --log meant for one run must not turn the log on for
// good, with a file per run and no rotation to clean up after it.
static struct {
	int enabled = -1;		// -1 = the config decides
	int console = -1;
	int level = -1;
	QString groups;
	QString dir;
} args;

static bool header_done = false;

// -------------------------------------------------------------- the columns

// The emulated clock for the F and T columns: frames since reset, T since the
// last interrupt. Called for every line, from either thread.
static void emu_time(int* frame, int* tick) {
	xProfile* prf = conf.prof.cur;
	Computer* comp = prf ? prf->zx : NULL;
	if (!comp) return;
	*frame = comp->frmCount;
	*tick = comp->frmtCount;
}

// ------------------------------------------------------------- Qt messages

static void qt_message(QtMsgType type, const QMessageLogContext& ctx, const QString& msg) {
	int lev = XLL_DEBUG;
	switch (type) {
		case QtDebugMsg: lev = XLL_DEBUG; break;
		case QtInfoMsg: lev = XLL_INFO; break;
		case QtWarningMsg: lev = XLL_WARN; break;
		case QtCriticalMsg:
		case QtFatalMsg: lev = XLL_ERROR; break;
	}
	if (xlog_on(XLG_GUI, lev)) {
		if (ctx.file && lev <= XLL_WARN) {
			xlog_put(XLG_GUI, lev, "%s (%s:%d)", msg.toUtf8().constData(), ctx.file, ctx.line);
		} else {
			xlog_put(XLG_GUI, lev, "%s", msg.toUtf8().constData());
		}
	}
	if (type == QtFatalMsg) abort();
}

// ------------------------------------------------------------ levels/groups

// A group holds XLOG_FOLLOW until something sets it apart, so the base level
// lives in one place and moving it needs no sweep over the groups.
//
// "video:trace,net:off,-sound" over the base level. "all:debug" moves the lot.
static void groups_parse(const QString& spec, int base, signed char* dst) {
	for (int i = 0; i < XLG_COUNT; i++)
		dst[i] = XLOG_FOLLOW;
	const QStringList items = spec.split(',', X_SkipEmptyParts);
	for (int i = 0; i < items.size(); i++) {
		QString item = items.at(i).trimmed();
		if (item.isEmpty()) continue;
		int lev = base;
		if (item.startsWith('-')) {
			item = item.mid(1);
			lev = XLL_OFF;
		} else if (item.contains(':')) {
			const QString lname = item.section(':', 1, 1).trimmed();
			item = item.section(':', 0, 0).trimmed();
			lev = xlog_level_id(lname.toUtf8().constData());
			if (lev < 0) {
				xlog(XLG_CONF, XLL_WARN, "log: unknown level '%s'", lname.toUtf8().constData());
				continue;
			}
		}
		if (item.compare("all", Qt::CaseInsensitive) == 0) {
			for (int g = 0; g < XLG_COUNT; g++)
				dst[g] = lev;
			continue;
		}
		int grp = xlog_group_id(item.toUtf8().constData());
		if (grp < 0) {
			xlog(XLG_CONF, XLL_WARN, "log: unknown group '%s'", item.toUtf8().constData());
			continue;
		}
		dst[grp] = lev;
	}
}

void log_groups_set(const QString& spec) {
	groups_parse(spec, conf.log.level, conf.log.grp);
}

static QString groups_str() {
	QStringList lst;
	for (int i = 0; i < XLG_COUNT; i++) {
		if (conf.log.grp[i] == XLOG_FOLLOW) continue;
		lst << QString("%1:%2").arg(xlog_group_name(i)).arg(xlog_level_name(conf.log.grp[i])).toLower();
	}
	return lst.join(",");
}

// ----------------------------------------------------------- the [LOG] section

void log_save(FILE* file) {
	fprintf(file, "enabled = %s\n", YESNO(conf.log.enabled));
	fprintf(file, "console = %s\n", YESNO(conf.log.console));
	fprintf(file, "level = %s\n", QString(xlog_level_name(conf.log.level)).toLower().toLocal8Bit().data());
	fprintf(file, "groups = %s\n", groups_str().toLocal8Bit().data());
	fprintf(file, "dir = %s\n", conf.log.dir.c_str());
}

bool log_load(const std::string& key, const char* val, bool flag) {
	if (key == "enabled") {
		conf.log.enabled = flag;
	} else if (key == "console") {
		conf.log.console = flag;
	} else if (key == "level") {
		int lev = xlog_level_id(val);
		if (lev >= 0) conf.log.level = lev;
	} else if (key == "groups") {
		log_groups_set(QString(val));
	} else if (key == "dir") {
		conf.log.dir = val;
	} else {
		return false;
	}
	return true;
}

// ------------------------------------------------------------- command line

static const char* take_value(const char* sw, int& n, int ac, char** av) {
	if (n < ac) return av[n++];
	xlog(XLG_APP, XLL_WARN, "%s needs a value", sw);
	return NULL;
}

bool log_arg(const char* arg, int& n, int ac, char** av) {
	const char* val;
	if (!strcmp(arg, "--log")) {
		args.enabled = 1;
	} else if (!strcmp(arg, "--no-log")) {
		args.enabled = 0;
	} else if (!strcmp(arg, "--log-console")) {
		args.console = 1;
	} else if (!strcmp(arg, "-c") || !strcmp(arg, "--console")) {
		// a console asked for by hand gets the same amount of talk as the
		// printf's this replaced, which were all unconditional
		args.console = 1;
		if (args.level < 0) args.level = XLL_DEBUG;
		return false;		// main still has to attach the thing
	} else if (!strcmp(arg, "--log-level")) {
		if (!(val = take_value(arg, n, ac, av))) return true;
		args.level = xlog_level_id(val);
		if (args.level < 0)
			xlog(XLG_APP, XLL_WARN, "--log-level: unknown level '%s'", val);
	} else if (!strcmp(arg, "--log-groups")) {
		if (!(val = take_value(arg, n, ac, av))) return true;
		args.groups = val;
	} else if (!strcmp(arg, "--log-dir")) {
		if (!(val = take_value(arg, n, ac, av))) return true;
		args.dir = val;
	} else {
		return false;
	}
	return true;
}

void log_args_clear() {
	args.enabled = -1;
	args.console = -1;
	args.level = -1;
	args.groups.clear();
	args.dir.clear();
}

// ------------------------------------------------------------------- header

static QString host_line() {
	QString s = QSysInfo::prettyProductName();
	if (s.isEmpty()) s = QSysInfo::productType();
	return QString("%1, %2 (%3 %4)")
		.arg(s)
		.arg(QSysInfo::currentCpuArchitecture())
		.arg(QSysInfo::kernelType())
		.arg(QSysInfo::kernelVersion());
}

static QString sdl_line() {
	SDL_version bld;
	SDL_VERSION(&bld);
#if SDL_MAJOR_VERSION >= 2
	SDL_version run;
	SDL_GetVersion(&run);
#else
	const SDL_version run = *SDL_Linked_Version();
#endif
	return QString("build %1.%2.%3, run %4.%5.%6")
		.arg(bld.major).arg(bld.minor).arg(bld.patch)
		.arg(run.major).arg(run.minor).arg(run.patch);
}

static QString screen_line() {
	QScreen* scr = QGuiApplication::primaryScreen();
	if (!scr) return "unknown";
	return QString("%1x%2 @ %3 Hz, dpr %4, %5 dpi")
		.arg(scr->geometry().width()).arg(scr->geometry().height())
		.arg(scr->refreshRate(), 0, 'f', 3)
		.arg(scr->devicePixelRatio(), 0, 'f', 2)
		.arg(scr->logicalDotsPerInch(), 0, 'f', 0);
}

static void put(const QString& s) {
	xlog_raw(QString("# " + s).toUtf8().constData());
}

static void write_header() {
	if (header_done) return;
	header_done = true;
	xlog_raw("# ---------------------------------------------------------------");
	put(QString("%1 %2").arg(XPRODUCT).arg(XVERSION));
	put(QString("started %1").arg(QDateTime::currentDateTime().toString("yyyy-MM-dd HH:mm:ss")));
	put(QString("command line: %1").arg(QCoreApplication::arguments().join(' ')));
	put(QString("host: %1").arg(host_line()));
	put(QString("qt: build %1, run %2").arg(QT_VERSION_STR).arg(qVersion()));
	put(QString("sdl: %1").arg(sdl_line()));
#ifdef HAVEZLIB
	put(QString("zlib: build %1").arg(ZLIB_VERSION));
#endif
	put(QString("screen: %1").arg(screen_line()));
	put(QString("config: %1").arg(QString::fromStdString(conf.path.confDir)));
	put(QString("profile: %1").arg(conf.prof.cur ? QString::fromStdString(conf.prof.cur->name) : QString("none")));
	QString lvls;
	for (int i = 0; i < XLG_COUNT; i++)
		lvls += QString("%1%2:%3").arg(i ? " " : "").arg(xlog_group_name(i)).arg(xlog_level_name(xlog_lev[i]));
	put(QString("levels: %1").arg(lvls.toLower()));
	put("columns: time elapsed frame tick level group message");
	xlog_raw("# ---------------------------------------------------------------");
}

// --------------------------------------------------------------- open/close

QString log_dir() {
	const QString path = log_file();
	return path.isEmpty() ? QString() : QFileInfo(path).absolutePath();
}

QString log_file() {
	return xlog_is_open() ? QString::fromUtf8(xlog_path()) : QString();
}

// Where logs/ goes: whatever was asked for, else beside the binary. A read-only
// install (AppImage, a macOS bundle, Program Files) falls back to the config
// directory, which is always ours to write in. Opening the file is the only
// test of that - a probe would just create and delete the same file twice.
static bool open_file(const QString& want_dir) {
	const QDateTime now = QDateTime::currentDateTime();
	const QString name = QString("%1-%2.log").arg(XPKGNAME).arg(now.toString("yyyyMMdd-HHmmss"));
	QStringList bases;
	if (!want_dir.isEmpty()) bases << want_dir;
	bases << QCoreApplication::applicationDirPath();
	bases << QString::fromStdString(conf.path.confDir);
	for (int i = 0; i < bases.size(); i++) {
		if (bases.at(i).isEmpty()) continue;
		const QString dir = QDir(bases.at(i)).filePath("logs/" + now.toString("yyyy-MM-dd"));
		if (!QDir().mkpath(dir)) continue;
		if (xlog_open(QDir(dir).filePath(name).toLocal8Bit().constData()))
			return true;
	}
	xlog(XLG_APP, XLL_ERROR, "log: no writable place for it, tried %s",
		bases.join(", ").toUtf8().constData());
	return false;
}

// Writing to a stdout nobody is reading still costs the whole line. On Windows
// the app is a GUI subsystem binary, so without -c there is no handle at all.
static bool console_alive() {
#ifdef _WIN32
	return GetStdHandle(STD_OUTPUT_HANDLE) != NULL;
#else
	return true;
#endif
}

void log_init() {
	xlog_init();
	xlog_set_emutime(emu_time);	// the clock comes from pacingInit
	qInstallMessageHandler(qt_message);
	conf.log.enabled = 0;
	conf.log.console = 1;		// where the printf's this replaces went
	conf.log.level = XLL_INFO;
	for (int i = 0; i < XLG_COUNT; i++)
		conf.log.grp[i] = XLOG_FOLLOW;
}

void log_apply() {
	// conf.log is what the config file and the options page hold; the command
	// line is an overlay on top of it that is never written back
	const bool enabled = (args.enabled >= 0) ? args.enabled : conf.log.enabled;
	const bool console = ((args.console >= 0) ? args.console : conf.log.console) && console_alive();
	const int base = (args.level >= 0) ? args.level : conf.log.level;
	const QString dir = args.dir.isEmpty() ? QString::fromStdString(conf.log.dir) : args.dir;

	xlog_set_console(console ? 1 : 0);

	if (enabled && !xlog_is_open()) {
		open_file(dir);
	} else if (!enabled && xlog_is_open()) {
		xlog(XLG_APP, XLL_INFO, "log: closed");
		xlog_close();
	}

	// --log-groups replaces the config's group list for this run rather than
	// merging with it: one place to look when the two disagree
	signed char grp[XLG_COUNT];
	if (args.groups.isEmpty()) {
		memcpy(grp, conf.log.grp, sizeof(grp));
	} else {
		groups_parse(args.groups, base, grp);
	}

	// levels last: the lines above belong in the file that just opened
	const bool live = xlog_is_open() || console;
	for (int i = 0; i < XLG_COUNT; i++)
		xlog_lev[i] = live ? ((grp[i] == XLOG_FOLLOW) ? base : grp[i]) : XLL_OFF;

	if (xlog_is_open() || console)
		write_header();
	xlog_flush_early();
}

void log_done() {
	xlog(XLG_APP, XLL_INFO, "stopped");
	xlog_done();
}
