#include <QMatrix4x4>
#include <QCursor>
#include <QTimer>
#include <QMenu>
#include <QMenuBar>
#include <QMessageBox>
#include <QProgressBar>
#include <QTableWidget>
#include <QTime>
#include <QUrl>
#include <QMimeData>
#include <QPainter>
#include <QFileDialog>
#include <QGuiApplication>

#include <QDebug>

// QDesktopWidget removed in Qt6
#if QT_VERSION < QT_VERSION_CHECK(6,0,0)
	#include <QDesktopWidget>
#endif

#include <fstream>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>

#include "xcore/xcore.h"
#include "xcore/sound.h"
#include "xcore/autostart.h"
#include "emulwin.h"
#include "filer.h"
#include "watcher.h"

#include "xcore/vfilters.h"
#include "xcore/vscalers.h"

#include "version.h"		// generated by CMake

#define	XPTITLE	XPRODUCT " (" XVERSION ")"
#define	FPS_TICK_MS	200		// the timer the fps readout is sampled on

#if defined(__WIN32)
#include <windows.h>
#include <winuser.h>
#endif

// mainwin

void MainWin::updateHead() {
	QString title(XPTITLE);
#ifdef ISDEBUG
	title.append(" | debug");
#endif
	if (conf.prof.cur) {
		title.append(" | ").append(conf.prof.cur->name.c_str());
		title.append(" | ").append(conf.prof.cur->layName.c_str());
	}
	if (conf.emu.fast) {
		title.append(" | fast");
	}
	setWindowTitle(title);
}

void MainWin::updateWindow() {
	block = 1;
	// the texture still holds the frame cut to the old bounds, and painting it
	// into the resized window would stretch it until the next frame arrives
	refit = 1;
	QSize wsz;
	Computer* comp = conf.prof.cur->zx;
	vid_set_zoom(conf.vid.scale);		// where the picture goes, and how big
	// a size change can switch the shader off or bring it back (wantedShader)
	if (conf.vid.shd_support && (wantedShader() != shdLoaded))
		loadShader();
	blockSignals(true);
	if (conf.vid.fullScreen) {
		wsz = SCREENSIZE;
		setWindowState(windowState() | Qt::WindowFullScreen);
	} else {
		// the window is the picture: a whole number of pixels per dot, or it
		// would be resampled and some columns come out a pixel wider than others
		wsz = QSize(drawW, drawH);
		setWindowState(windowState() & ~Qt::WindowFullScreen);
	}
	setFixedSize(wsz);
	blockSignals(false);
	// the buffer holds the whole raster, whatever part of it is shown
	bytesPerLine = comp->vid->full.x * 8;
	bufSize = bytesPerLine * comp->vid->full.y * (comp->vid->linedbl ? 2 : 1);
	updateHead();
	block = 0;
}

bool MainWin::saveChanged() {
	xProfile* prf;
	bool yep = true;
	int res;
	int i;
	QString str;
	Floppy* flp;
	foreach(prf, conf.prof.list) {
		if (!prf->initrq) {
			for(i = 0; (i < 4) && yep; i++) {
				flp = prf->zx->dif->flp[i];
				if (flp->changed) {
					str = QString("Disk %0 of profile '%1' was changed<br>Save it?").arg(QChar('A' + i)).arg(prf->name.c_str());
					res = askYNC(str.toLocal8Bit().data());
					switch(res) {
						case QMessageBox::Yes:
							yep &= save_file(prf->zx, flp->path, FG_DISK, i);
							break;
						case QMessageBox::Cancel:
							yep = false;
							break;
					}
				}
			}
		}
		if (!yep) break;
	}
	return yep;
}

void MainWin::pause(bool p, int msk) {
	conf.emu.fast = 0;
	if (p) {
		conf.emu.pause |= msk;
	} else {
		conf.emu.pause &= ~msk;
	}
	if (!grabMice || (conf.emu.pause && grabMice)) {
		releaseMouse();
	}
	if (conf.emu.pause) {
		setWindowIcon(QIcon(":/images/pause.png"));
	} else {
		setWindowIcon(icon);
		if (grabMice)
			grabMouse(QCursor(Qt::BlankCursor));
	}
}

// Main window

MainWin::MainWin() {
	qDebug() << "constructor";

	setWindowTitle(XPTITLE);
	setMouseTracking(true);
	icon = QGuiApplication::windowIcon();
	setWindowIcon(icon);
	setAcceptDrops(true);
	// setAutoFillBackground(false);
	setUpdatesEnabled(false);
	conf.emu.pause = 0;
	scrCounter = 0;
	scrInterval = 0;
	grabMice = 0;
	block = 0;
	hasPicture = 0;
	refit = 0;
//	relskip = 0;

	msgTimer = 0;
	msg.clear();
	alphabet.load(":/font.png");

	shotFormat["bmp"] = SCR_BMP;
	shotFormat["png"] = SCR_PNG;
	shotFormat["jpg"] = SCR_JPG;
	shotFormat["scr"] = SCR_SCR;
	shotFormat["hobeta"] = SCR_HOB;

	leds[led_kbd].load(":/images/scanled.png");
	leds[led_joy].load(":/images/joystick.png");
	leds[led_mouse].load(":/images/mouse.png");
	leds[led_tap_red].load(":/images/tapeRed.png");
	leds[led_tap_yellow].load(":/images/tapeYellow.png");
	leds[led_disk_green].load(":/images/diskGreen.png");
	leds[led_disk_red].load(":/images/diskRed.png");
	leds[led_wav].load(":/images/wav.png");

//	conf.joy.gpad->open(); // conf.joy.curName);

	connect(conf.gpctrl->gpada, SIGNAL(buttonChanged(int,bool)), this, SLOT(gpButtonChanged(int,bool)));
	connect(conf.gpctrl->gpada, SIGNAL(axisChanged(int,double)), this, SLOT(gpAxisChanged(int,double)));
	connect(conf.gpctrl->gpadb, SIGNAL(buttonChanged(int,bool)), this, SLOT(gpButtonChanged(int,bool)));
	connect(conf.gpctrl->gpadb, SIGNAL(axisChanged(int,double)), this, SLOT(gpAxisChanged(int,double)));

	initFileDialog(this);
	initUserMenu();
	setFocus();

	frm_ns = 0;
	timid = startTimer(20);		// 1/50 sec
	secid = startTimer(FPS_TICK_MS);	// 1/5 sec
	cmsid = startTimer(1000);	// 1 sec

	connect(&frm_tmr, SIGNAL(timeout()), this, SLOT(frame_timer()));
#if QT_VERSION >= QT_VERSION_CHECK(5,0,0)
	frm_tmr.setTimerType(Qt::PreciseTimer);
#endif
	frm_tmr.start(20);

	connect(userMenu,SIGNAL(aboutToShow()),SLOT(menuShow()));
	connect(userMenu,SIGNAL(aboutToHide()),SLOT(menuHide()));
	fillUserMenu();

#ifdef __APPLE__
	// Cocoa always gives the app a menu bar, even though this app never creates a
	// QMenuBar, and that menu already binds Cmd+Q to its own stub Quit item. Qt's
	// menu-role merging only replaces that stub with an app-supplied QuitRole action
	// when the action lives inside an actual QMenu/QMenuBar - a bare QAction on a
	// widget (tried first) never enters that tree, so the stub kept catching Cmd+Q.
	// An unparented QMenuBar becomes the app's default menu bar on macOS without
	// ever showing as an in-window menu on Windows/Linux.
	QMenuBar* macMenuBar = new QMenuBar(nullptr);
	QMenu* macAppMenu = macMenuBar->addMenu(QString());
	QAction* quitAct = macAppMenu->addAction(tr("Quit"));
	quitAct->setMenuRole(QAction::QuitRole);
	quitAct->setShortcut(QKeySequence::Quit);
	connect(quitAct, &QAction::triggered, this, &QWidget::close);
#endif

#ifdef USENETWORK
	openServer();
	connect(&srv, SIGNAL(newConnection()),this, SLOT(connected()));
#endif

#if defined(USEOPENGL) && !BLOCKGL
	// initializeGL creates the shaders, and it only runs when the window is
	// first shown. Exiting before that - "xpeccy-plus --help" does - would
	// otherwise leave the destructor deleting an uninitialized pointer.
	vtx_shd = NULL;
	frg_shd = NULL;
#endif

// a legacygl code must be here, else the main process doesn't finish properly (???)
#if USELEGACYGL
	QGLFormat frmt;
	frmt.setDoubleBuffer(false);
	cont = new QGLContext(frmt);
	setContext(cont);
	setAutoBufferSwap(true);
	makeCurrent();
	curtex = 0;
	shd_support = QGLShader::hasOpenGLShaders(QGLShader::Vertex) && QGLShader::hasOpenGLShaders(QGLShader::Fragment);
	qDebug() << "vtx_shd";
	vtx_shd = new QGLShader(QGLShader::Vertex, cont);
	qDebug() << "frg_shd";
	frg_shd = new QGLShader(QGLShader::Fragment, cont);
#endif

	qDebug() << "end:constructor";
}

MainWin::~MainWin() {
#if defined(USEOPENGL) && !BLOCKGL
	cleanupGL();
	delete(vtx_shd);
	delete(frg_shd);
#endif
}

// gamepad mapper
// xJoyMapEntry::key is XKEY_*

void MainWin::mapRelease(Computer* comp, xJoyMapEntry ent) {
	Qt::Key key;
	Qt::KeyboardModifier mod;
	int xkey;
	switch(ent.dev) {
		case JMAP_KEY:
#if !USE_SEQ_BIND
			xkey_release(ent.key);
#else
			for(int i = 0; i < ent.seq.count(); i++) {
				key = Qt::Key(ent.seq[i] & ~Qt::KeyboardModifierMask);
				mod = Qt::KeyboardModifier(ent.seq[i] & Qt::KeyboardModifierMask);
				xkey = qKey2id(key, mod);
				if (mod & Qt::ShiftModifier) {xkey_release(XKEY_LSHIFT);}
				if (mod & Qt::ControlModifier) {xkey_release(XKEY_LCTRL);}
				if (mod & Qt::AltModifier) {xkey_release(XKEY_LALT);}
				xkey_release(xkey);
			}
#endif
			break;
		case JMAP_JOY:
			joyRelease(comp->joy, ent.dir);
			break;
		case JMAP_JOYB:
			joyRelease(comp->joyb, ent.dir);
			break;
		case JMAP_MOUSE:
			mouseRelease(comp->mouse, ent.dir);
			break;
	}
}

void MainWin::mapPress(Computer* comp, xJoyMapEntry ent) {
	Qt::Key key;
	Qt::KeyboardModifier mod;
	int xkey;
	switch(ent.dev) {
		case JMAP_KEY:
#if !USE_SEQ_BIND
			xkey_press(ent.key);
#else
			for(int i = 0; i < ent.seq.count(); i++) {
				key = Qt::Key(ent.seq[i] & ~Qt::KeyboardModifierMask);
				mod = Qt::KeyboardModifier(ent.seq[i] & Qt::KeyboardModifierMask);
				xkey = qKey2id(key, mod);
				//qDebug() << ent.seq[i] << key << mod << xkey;
				if (mod & Qt::ShiftModifier) {xkey_press(XKEY_LSHIFT);}
				if (mod & Qt::ControlModifier) {xkey_press(XKEY_LCTRL);}
				if (mod & Qt::AltModifier) {xkey_press(XKEY_LALT);}
				xkey_press(xkey);
			}
#endif
			break;
		case JMAP_JOY:
			joyPress(comp->joy, ent.dir);
			break;
		case JMAP_JOYB:
			joyPress(comp->joyb, ent.dir);
			break;
		case JMAP_MOUSE:
			mousePress(comp->mouse, ent.dir, abs(ent.state / 4096));
			break;
	}
}

// TODO: choose gamepad (gpad/gpadb)
void MainWin::mapJoystick(xGamepad* gp, Computer* comp, int type, int num, int st) {
	QList<xJoyMapEntry> presslist = gp->scanMap(type, num, st);
#if 0
	int state;
	int hst;
	if (type == JOY_HAT) {
		state = st;
		hst = jState[type][num] ^ st;		// changed only
	} else {
		state = sign(st);
		hst = 0;
	}
	if (jState[type][num] == state) return;
	jState[type][num] = state;
	// xJoyMapEntry xjm;
	QList<xJoyMapEntry> presslist;
	// QList<xJoyMapEntry>::iterator it;
	for (int i = 0; i < gp->map.size(); i++) {
		xJoyMapEntry& xjm = gp->map[i];
		if ((type == xjm.type) && (num == xjm.num)) {
			if ((state == 0) && (type != JOY_HAT)) {
				mapRelease(comp, xjm);
				xjm.cnt = 0;
			} else {
				switch(type) {
					case JOY_AXIS:
						if (sign(state) == sign(xjm.state)) {
							xjm.state = st;
							xjm.cnt = xjm.rpt;
							xjm.rps = 1;
							presslist.append(xjm);
						} else {
							xjm.cnt = 0;
							mapRelease(comp, xjm);
						}
						break;
					case JOY_HAT:
						if (hst & xjm.state) {			// state changed
							if (state & xjm.state) {	// pressed
								xjm.cnt = xjm.rpt;
								xjm.rps = 1;
								presslist.append(xjm);
							} else {			// released
								xjm.cnt = 0;
								mapRelease(comp, xjm);
							}
						}
						break;
					case JOY_BUTTON:
						xjm.cnt = xjm.rpt;
						xjm.rps = 1;
						presslist.append(xjm);
						break;
				}
			}
		}
	}
#endif
	foreach(xJoyMapEntry xjm, presslist) {
		if (xjm.rps) {
			mapPress(comp, xjm);
		} else {
			mapRelease(comp, xjm);
		}
	}
}

// for xGamepad

// A,B,X,Y,L1,L3,R1,R3,Up,Down,Left,Right,Start,Select,Center,Guide
void MainWin::gpButtonChanged(int n, bool v) {
	if (conf.emu.pause) return;
	if (!isActiveWindow()) return;
	xGamepad* gp = (xGamepad*)sender();
	mapJoystick(gp, conf.prof.cur->zx, JOY_BUTTON, n, v);
}
// LX,LY,Rx,RY,L2,R2
void MainWin::gpAxisChanged(int n, double v) {
	if (conf.emu.pause) return;
	if (!isActiveWindow()) return;
	xGamepad* gp = (xGamepad*)sender();
	mapJoystick(gp, conf.prof.cur->zx, JOY_AXIS, n, v * 32767);
}

// calling on timer every 20ms

// fps sampling window. Both ends are taken at a frame boundary - the count and
// the time of that same frame - so the reading has no rounding of its own.
struct FpsSample { int frames; qint64 ns; };
static QList<FpsSample> fpsmem;
#define FPS_WINDOW	(3000 / FPS_TICK_MS)	// samples kept: a 3 second window

#if defined(__WIN32) && STICKY_KEY

static struct {
	int vkey;
	int state;
	int qkey;		// Qt::Key
	qint32 nCode;		// nativeScanCode = XKEY_* on windows
} win_mod_tab[6] = {
	{VK_RSHIFT, 0, Qt::Key_Shift, XKEY_RSHIFT},
	{VK_LSHIFT, 0, Qt::Key_Shift, XKEY_LSHIFT},
	{VK_RCONTROL, 0, Qt::Key_Control, XKEY_RCTRL},
	{VK_LCONTROL, 0, Qt::Key_Control, XKEY_LCTRL},
	{VK_RMENU, 0, Qt::Key_Alt, XKEY_RALT},
	{VK_LMENU, 0, Qt::Key_Alt, XKEY_LALT}
};

#endif

void MainWin::timerEvent(QTimerEvent* ev) {
	Computer* comp = conf.prof.cur->zx;
	if (ev->timerId() == secid) {		// 0.2 sec timer, fps counter
		// printf("0.2 sec timer event\n");
		if (!conf.emu.pause && conf.vid.fctime) {
			FpsSample cur = {conf.vid.fcount, conf.vid.fctime};
			fpsmem.append(cur);
			qint64 dtNs = cur.ns - fpsmem.first().ns;
			int dFrames = cur.frames - fpsmem.first().frames;
			conf.vid.curfps = (dtNs > 0) ? (dFrames * 1e9 / dtNs) : 0.0;
			while (fpsmem.size() > FPS_WINDOW)
				fpsmem.removeFirst();
		} else {
			// no frames are made while paused (emuCycle() itself checks
			// conf.emu.pause), so a stale pre-pause sample would otherwise sit
			// at fpsmem.first() and drag the average down across the whole
			// pause - drop the window instead of letting it slide out one
			// entry at a time after resuming.
			fpsmem.clear();
		}
		if (comp->vid->upd) {
			comp->vid->upd = 0;
			updateWindow();
		}
	} else if (ev->timerId() == cmsid) {	// 1-sec: cmos interrupt
		// TODO: do
	} else if (ev->timerId() == timid) {
// updater
//		if (conf.prof.changed) {
//			comp = conf.prof.cur->zx;
//			conf.prof.changed = 0;
//		}
		if (block) return;
#if HAVEZLIB
		if (comp->rzx.start) {
			emit s_rzx_start();
		} else if (comp->rzx.stop) {
			emit s_rzx_stop();
		}
		if (comp->rzx.overio) {
			comp->rzx.overio = 0;
			pause(true, PR_RZX);
			shitHappens("RZX playback error");
			emit s_rzx_stop();
			pause(false, PR_RZX);
		}
#endif
// buttons autorepeat switcher (added: for 2nd gamepad too)
		QList<xJoyMapEntry> presslist = conf.gpctrl->gpada->repTick();
		xJoyMapEntry xjm;
		foreach(xjm, presslist) {
			if (xjm.rps) {
				mapPress(comp, xjm);
			} else {
				mapRelease(comp, xjm);
			}
		}
		presslist = conf.gpctrl->gpadb->repTick();
		foreach(xjm, presslist) {
			if (xjm.rps) {
				mapPress(comp, xjm);
			} else {
				mapRelease(comp, xjm);
			}
		}
#if 0
		for (int i = 0; i < conf.joy.gpad->map.size(); i++) {
			xJoyMapEntry& xjm = conf.joy.gpad->map[i];
			if (xjm.cnt > 0) {
				xjm.cnt--;
				if (xjm.cnt == 0) {
					xjm.cnt = xjm.rpt;
					xjm.rps = !xjm.rps;
					if (xjm.rps) {
						mapPress(comp, xjm);
					} else {
						mapRelease(comp, xjm);
					}
				}
			}
		}
#endif
// process mouse auto move
		comp->mouse->xpos += comp->mouse->autox;
		comp->mouse->ypos += comp->mouse->autoy;
// if computer sends a message, show it
		if (comp->msg) {
			setMessage(QString(comp->msg));
			comp->msg = NULL;
		}
// satelites
		updateSatellites();
#if defined(__WIN32) && STICKY_KEY
		if (!conf.emu.pause && isActiveWindow()) {		// if not paused (!)
			int state;
			QKeyEvent* ev;
			// events: nativeScanCode = 0, nativeVirtualKey = XKEY_*
			for (int i = 0; i < 6; i++) {
				state = GetKeyState(win_mod_tab[i].vkey) & 0x8000;
				if (state != win_mod_tab[i].state) {	// state changed
					if (state) {			// press
						ev = new QKeyEvent(QKeyEvent::KeyPress, win_mod_tab[i].qkey, Qt::NoModifier, 0, win_mod_tab[i].nCode, 0);
					} else {			// release
						ev = new QKeyEvent(QKeyEvent::KeyRelease, win_mod_tab[i].qkey, Qt::NoModifier, 0, win_mod_tab[i].nCode, 0);
					}
					QApplication::postEvent(this, ev);
					win_mod_tab[i].state = state;
				}
			}
		}
#endif
	}
}

// if window is not active release keys & buttons, release mouse
void MainWin::focusOutEvent(QFocusEvent*) {
	Computer* comp = conf.prof.cur->zx;
	mouseReleaseAll(comp->mouse);
	unsetCursor();
	if (grabMice) {
		grabMice = 0;
		releaseMouse();
	}
	emit s_keywin_rall(comp->keyb);
}

void MainWin::focusInEvent(QFocusEvent*) {
	if (conf.emu.pause & PR_DEBUG)
		emit s_debug();
	if (grabMice) {
		dumove = 1;
		cursor().setPos(pos() + QPoint(width()/2, height()/2));
	}
}

void MainWin::moveEvent(QMoveEvent* ev) {
	conf.xpos = pos().x();
	conf.ypos = pos().y();
}

void MainWin::menuShow() {
	Computer* comp = conf.prof.cur->zx;
	layoutMenu->setDisabled(comp->hw->lay != NULL);
	pause(true,PR_MENU);
}

void MainWin::menuHide() {
	setFocus();
	pause(false,PR_MENU);
}


// connection between tape window & tape state

void MainWin::tapStateChanged(int wut, int val) {
	Computer* comp = conf.prof.cur->zx;
	switch(wut) {
		case TW_STATE:
			switch(val) {
				case TWS_PLAY:
					tapUserPlay(comp->tape);
					emit s_tape_upd(comp->tape);
					break;
				case TWS_STOP:
					tapStop(comp->tape);
					emit s_tape_upd(comp->tape);
					break;
				case TWS_REC:
					tapRec(comp->tape);
					emit s_tape_upd(comp->tape);
					break;
				case TWS_OPEN:
					pause(true,PR_FILE);
					load_file(comp, NULL, FG_TAPE, -1);
					emit s_tape_upd(comp->tape);
					pause(false,PR_FILE);
					break;
			}
			break;
		case TW_REWIND:
			tapRewind(comp->tape,val);
			emit s_tape_upd(comp->tape);
			break;
		case TW_BREAK:
			comp->tape->blkData[val].breakPoint ^= 1;
			emit s_tape_upd(comp->tape);
			break;
	}
}

// connection between rzx player and emulation state
void MainWin::rzxStateChanged(int state) {
#ifdef HAVEZLIB
	Computer* comp = conf.prof.cur->zx;
	switch(state) {
		case RWS_PLAY:
			comp->rzx.start = 0;
			pause(false,PR_RZX);
			break;
		case RWS_PAUSE:
			pause(true,PR_RZX);
			break;
		case RWS_STOP:
			rzxStop(comp);
			comp->rzx.stop = 0;
			pause(false,PR_RZX);
			break;
		case RWS_OPEN:
			pause(true,PR_RZX);
			load_file(comp, NULL, FG_RZX, -1);
			if (comp->rzx.play) {
				emit s_rzx_start();
			}
			pause(false,PR_RZX);
			break;
	}
#endif
}

// Hand the shown part of the raster to the texture. The rest of the buffer is
// skipped by the unpack settings, so the frame stays whole in memory and can be
// read out again with new bounds - that is what makes a border change take
// effect at once, even while the machine is paused.
void MainWin::uploadFrame() {
#if defined(USEOPENGL) && !BLOCKGL
	Computer* comp = conf.prof.cur->zx;
	Video* vid = comp->vid;
	// GL_UNPACK_ROW_LENGTH and friends are core in GL 3.3 and GLES 3.0, which
	// is what the shaders here ask for anyway ("#version 330" / "300 es"), so
	// a context that has no unpack settings could not draw the picture either
	glPixelStorei(GL_UNPACK_ROW_LENGTH, vid->full.x * 2);
	glPixelStorei(GL_UNPACK_SKIP_PIXELS, vid->lcut.x * 2);
	glPixelStorei(GL_UNPACK_SKIP_ROWS, vid->lcut.y);
	glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, vid->vsze.x * 2, vid->vsze.y, 0,
		GL_RGBA, GL_UNSIGNED_BYTE, comp->flgDBG ? scrimg : bufimg);
	glPixelStorei(GL_UNPACK_ROW_LENGTH, 0);
	glPixelStorei(GL_UNPACK_SKIP_PIXELS, 0);
	glPixelStorei(GL_UNPACK_SKIP_ROWS, 0);
#endif
}

// Redraw now. blockSignals/setUpdatesEnabled avoids the QOpenGLWidget
// repaint recursion (see paintEvent).
void MainWin::presentFrame() {
	blockSignals(true);
	setUpdatesEnabled(true);
	repaint();
	setUpdatesEnabled(false);
	blockSignals(false);
}

void MainWin::frame_timer() {
	// No frame yet, so there is nothing in the window - and a window that is
	// never painted is not put on screen at all on macOS. Paint it anyway; no
	// frame is coming meanwhile, so the picture holds still. Autostart is the
	// long case: it runs the machine at full speed and draws no pixels.
	if (!hasPicture) {
		presentFrame();
		return;
	}
	// autostart draws nothing, but vid_frame() still swaps scrimg/bufimg every
	// frame: painting here would alternate between two stale buffers and flicker
	if (autostart_busy()) return;
	Computer* comp = conf.prof.cur->zx;
	if (comp) {
		frm_ns += comp->vid->nsPerFrame;
		frm_tmr.setInterval(frm_ns / 1000000);		// 1e6 ns = 1 ms. next frame shot
		frm_ns = frm_ns % 1000000;			// remains
	}
	// In low latency mode d_frame() shows each frame as soon as it is made,
	// so this timer does not paint in normal play (a second timer would beat
	// with frame making and cause a slow frame slip). The timer paints for
	// fast-forward and pause (no frames at 50Hz), and in buffered mode, where
	// a steady timer rate looks smoother.
	if (conf.vid.lowLatency && !conf.emu.fast && !conf.emu.pause) return;
#if defined(USEOPENGL) && !BLOCKGL
	if (conf.emu.fast || conf.emu.pause) {
		glBindTexture(GL_TEXTURE_2D, texids[curtex]);
		uploadFrame();
		queue.clear();
		queue.append(texids[curtex]);
	}
#endif
	presentFrame();
}

void MainWin::d_frame() {
	if (conf.emu.fast) return;
	hasPicture = 1;
#if defined(USEOPENGL) && !BLOCKGL
	queue.append(texids[curtex]);
	// Low latency keeps only the newest frame; buffered keeps a couple to
	// smooth jitter (see paintEvent).
	if (queue.size() > (conf.vid.lowLatency ? 1 : 2))
		queue.takeFirst();
	glBindTexture(GL_TEXTURE_2D, texids[curtex]);
	uploadFrame();
	curtex++;
#endif
	// Low latency: show the frame now. Buffered: let the timer show it.
	if (conf.vid.lowLatency)
		presentFrame();
}

static char numbuf[32];

void MainWin::drawText(QPainter* pnt, int x, int y, const char* buf) {
	size_t len = strlen(buf);
	for (size_t i = 0; i < len; i++) {
		pnt->drawImage(x, y, alphabet, 0, (buf[i] - 32) * 12, 12, 12);
		x += 12;
	}
}

// bug? QOpenGLWidget crash during show->event (ResizeEvent): calling random slot-signal connection
// repaint/update causes recursion on QOpenGLWidget (whyyyyy?) even if there no paintEvent/paingGL
// if paintEvent exists, paintGL do not called

void MainWin::paintEvent(QPaintEvent*) {
	QPainter pnt(this);
#if defined(USEOPENGL) && !BLOCKGL
	pnt.beginNativePainting();
	glClearColor(0, 0, 0, 1);
	glClear(GL_COLOR_BUFFER_BIT);

	// Low latency: take the newest frame and drop the rest for the lowest
	// lag. Buffered: take the oldest (FIFO) so the small buffer smooths jitter.
	if (!queue.isEmpty()) {
		if (conf.vid.lowLatency) {
			curtxid = queue.takeLast();
			queue.clear();
		} else {
			curtxid = queue.takeFirst();
		}
	}

	// The window (or the border) has just changed. Read the frame out of the
	// buffer again with the new bounds instead of stretching the old texture
	// over the new window - and while the machine is paused, no new frame is
	// coming to do it later.
	if (refit && prg.isLinked()) {		// isLinked: initializeGL has run, texids are real
		refit = 0;
		glBindTexture(GL_TEXTURE_2D, texids[curtex]);
		uploadFrame();
		curtxid = texids[curtex];
		queue.clear();
	}

	// curtxid stays 0 until the emulation thread hands over its first frame,
	// and the window is painted before that happens. Binding a texture name
	// that was never generated is undefined - macOS says so out loud, other
	// drivers quietly sample black.
	if (prg.isLinked() && curtxid) {
		const qreal r = widgetDpr(this);
		Computer* comp = conf.prof.cur->zx;
		const GLfloat tex_w = GLfloat(comp->vid->vsze.x * 2);
		const GLfloat tex_h = GLfloat(comp->vid->vsze.y);
		// the quad covers the viewport, and the viewport is the picture: in
		// fullscreen it is a whole-zoom rectangle in the middle of the screen,
		// with the cleared black around it
		glViewport(int(drawX * r + 0.5), int(drawY * r + 0.5),
			int(drawW * r + 0.5), int(drawH * r + 0.5));
		static const QMatrix4x4 legacyMvp = []{
			QMatrix4x4 m;
			m.ortho(0.0f, 1.0f, 1.0f, 0.0f, -1.0f, 1.0f);
			return m;
		}();
		prg.bind();
		prg.setUniformValue("u_tex", 0);
		prg.setUniformValue("rubyTexture", 0);
		prg.setUniformValue("u_mvp_", legacyMvp);
		prg.setUniformValue("rubyInputSize",   tex_w, tex_h);
		prg.setUniformValue("rubyTextureSize", tex_w, tex_h);
		prg.setUniformValue("rubyOutputSize",  GLfloat(drawW * r), GLfloat(drawH * r));

		glActiveTexture(GL_TEXTURE0);
		glBindTexture(GL_TEXTURE_2D, curtxid);

		vao.bind();
		glDrawArrays(GL_TRIANGLE_STRIP, 0, 4);
		vao.release();

		prg.release();
	}
	glFlush();
	pnt.endNativePainting();
#else
	// same buffer as the GL path, scaled here instead. No smooth transform, so
	// a dot stays a block of whole pixels.
	Computer* comp = conf.prof.cur->zx;
	Video* vid = comp->vid;
	QImage img(comp->flgDBG ? scrimg : bufimg, vid->full.x * 2, bufSize / bytesPerLine, bytesPerLine, QImage::Format_RGBA8888);
	pnt.drawImage(QRect(drawX, drawY, drawW, drawH), img,
		QRect(vid->lcut.x * 2, vid->lcut.y, vid->vsze.x * 2, vid->vsze.y));
#endif
	drawIcons(pnt);
	pnt.end();
}

void MainWin::drawIcons(QPainter& pnt) {
	Computer* comp = conf.prof.cur->zx;
// screenshot
	if (scrCounter > 0) {
		if (scrInterval > 0) {
			scrInterval--;
		} else {
			scrInterval = conf.scrShot.interval;
			scrCounter--;
			screenShot();
		}
	}
// put leds
// keyboard
	if (conf.led.keys && (comp->hw->grp == HWG_ZX)) {
		pnt.drawImage(3, 10, leds[led_kbd]);
		if (~comp->keyb->port & 0x01) pnt.fillRect(3 + 3, 10 + 17, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x02) pnt.fillRect(3 + 3, 10 + 14, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x04) pnt.fillRect(3 + 3, 10 + 11, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x08) pnt.fillRect(3 + 3, 10 + 8, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x80) pnt.fillRect(3 + 12, 10 + 17, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x40) pnt.fillRect(3 + 12, 10 + 14, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x20) pnt.fillRect(3 + 12, 10 + 11, 8, 2, Qt::gray);
		if (~comp->keyb->port & 0x10) pnt.fillRect(3 + 12, 10 + 8, 8, 2, Qt::gray);
	}
	comp->keyb->port = 0xff;
// joystick
	if (comp->joy->used && conf.led.joy) {
		pnt.drawImage(3, 30, leds[led_joy]);
		comp->joy->used = 0;
	}
// mouse
	if (comp->mouse->used && conf.led.mouse) {
		pnt.drawImage(3, 50, leds[led_mouse]);
		comp->mouse->used = 0;
	}
// tape
	if (comp->tape->on && conf.led.tape) {
		pnt.drawImage(3, 70, comp->tape->rec ? leds[led_tap_red] : leds[led_tap_yellow]);
	}
// disc
	if (conf.led.disk) {
		if (comp->dif->fdc->flp->rd) {
			comp->dif->fdc->flp->rd = 0;
			pnt.drawImage(3, 90, leds[led_disk_green]);
		} else if (comp->dif->fdc->flp->wr) {
			comp->dif->fdc->flp->wr = 0;
			pnt.drawImage(3, 90, leds[led_disk_red]);
		}
	}
// waveout
	if (conf.snd.wavout) {
		pnt.drawImage(3, 110, leds[led_wav]);
	}
// put fps
	if (conf.led.fps) {
		sprintf(numbuf, " %.1f ", conf.vid.curfps);
		drawText(&pnt, width() - (strlen(numbuf) * 12) - 5, 5, numbuf);
	}
// put halt counter
	if (conf.led.halt) {
		sprintf(numbuf, " %d : %d ",comp->hCount, comp->fCount);
		drawText(&pnt, width() - strlen(numbuf) * 12 - 8, height() - 20, numbuf);
	}
// put messages
	if (msgTimer > 0) {
		if (conf.led.message) {
			drawText(&pnt, 5, height() - 20, msg.toLocal8Bit().data());
		}
		msgTimer--;
	}
// end
}


// A copy, never a move: with shift held the file manager offers a move, and
// would delete the original once the drop is taken.
void MainWin::dragEnterEvent(QDragEnterEvent* ev) {
	if (!ev->mimeData()->hasUrls()) return;
	ev->setDropAction(Qt::CopyAction);
	ev->accept();
}

void MainWin::dropEvent(QDropEvent* ev) {
	if (!ev->mimeData()->hasUrls()) return;
	ev->setDropAction(Qt::CopyAction);
	ev->accept();
	// one drop is one medium: a second file would only land on top of the first
	QString fpath = ev->mimeData()->urls().first().toLocalFile();
	if (fpath.isEmpty()) return;		// something that is not a file here
	raise();
	activateWindow();
#if QT_VERSION >= QT_VERSION_CHECK(6,0,0)
	bool ask = ev->modifiers() & Qt::ShiftModifier;
#else
	bool ask = ev->keyboardModifiers() & Qt::ShiftModifier;
#endif
	if (ask) {
		// not from here: the application the file came from is still waiting
		// for this handler to return, and a menu holds it for as long as it is up
		QTimer::singleShot(0, this, [this, fpath](){dropAsk(fpath);});
	} else {
		openMedia(fpath, FG_ALL, 0, conf.autorun);
	}
}

// shift on a drop: this one file, run or just mounted
void MainWin::dropAsk(QString path) {
	QMenu menu(this);
	QAction* run = menu.addAction(QIcon(":/images/play.png"), "Run");
	menu.addAction(QIcon(":/images/cd.png"), "Mount");
	QAction* act = menu.exec(QCursor::pos());
	if (!act) return;
	openMedia(path, FG_ALL, 0, (act == run) ? 1 : 0);
}

// One way in for "the user opened a medium", whatever pointed at it: an empty
// path asks the file dialog. The machine is held while the file is read, and
// started right there - arming resets it anyway, so there is nothing to gain
// from letting it run a cycle first.
void MainWin::openMedia(const QString& path, int id, int drv, int run) {
	Computer* comp = conf.prof.cur->zx;
	QByteArray loc = path.toLocal8Bit();
	pause(true, PR_FILE);
	load_file(comp, path.isEmpty() ? NULL : loc.data(), id, drv);
	media_autorun(comp, run);
	pause(false, PR_FILE);
	checkState();
	emit s_tape_upd(comp->tape);
}


void MainWin::closeEvent(QCloseEvent* ev) {
	pause(true,PR_EXIT);
	Computer* comp = conf.prof.cur->zx;
	if (conf.confexit) {
		if (!areSure("Quit?")) {
			ev->ignore();
			pause(false, PR_EXIT);
			return;
		}
	}
//	std::string fname;
	foreach(xProfile* prf, conf.prof.list) {
		if (!prf->initrq) {
			prfSave(prf->name);
		}
	}
	if (saveChanged()) {
		snd_wav_close();
		frm_tmr.stop();
		killTimer(timid);
		killTimer(secid);
		ideCloseFiles(comp->ide);
		sdcCloseFile(comp->sdc);
		sltEject(comp->slot);		// this must save cartridge ram
		emit s_keywin_close();
		saveConfig();
#ifdef USENETWORK
		closeServer();
#endif
		emit s_emulwin_close();
		ev->accept();
	} else {
		ev->ignore();
		pause(false,PR_EXIT);
	}
}

void MainWin::checkState() {
#ifdef HAVEZLIB
	Computer* comp = conf.prof.cur->zx;
	if (comp->rzx.start) {
		emit s_rzx_start();
	} else if (comp->rzx.stop) {
		emit s_rzx_stop();
	}
		//rzxWin->startPlay();
#endif
	//emit s_tape_list(comp->tape);
	//tapeWin->buildList(comp->tape);
	//tapeWin->setCheck(comp->tape->block);
}

// ...

uchar hobHead[] = {'s','c','r','e','e','n',' ',' ','C',0,0,0,0x1b,0,0x1b,0xe7,0x81};	// last 2 bytes is crc

void MainWin::screenShot() {
	Computer* comp = conf.prof.cur->zx;
	int frm = shotFormat[conf.scrShot.format];
	std::string fext;
	switch (frm) {
		case SCR_BMP: fext = "bmp"; break;
		case SCR_PNG: fext = "png"; break;
		case SCR_JPG: fext = "jpg"; break;
		case SCR_SCR: fext = "scr"; break;
		case SCR_HOB: fext = "$C"; break;
	}
	QString fnams = QString(conf.scrShot.dir.c_str()).append(SLASH);
	fnams.append(QString("xpeccy_%0.%1").arg(QTime::currentTime().toString("HHmmss_zzz")).arg(fext.c_str()));
	std::string fnam(fnams.toUtf8().data());
	std::ofstream file;
	Video* vid = comp->vid;
	// the shown frame, taken out of the whole raster. The screen sits in the
	// middle of it, so there is no lopsided border left to trim.
	QImage img(bufimg, vid->full.x * 2, bufSize / bytesPerLine, bytesPerLine, QImage::Format_RGBA8888);
	img = img.copy(vid->lcut.x * 2, vid->lcut.y, vid->vsze.x * 2, vid->vsze.y);
	char* sptr = (char*)(comp->mem->ramData + (comp->vid->vidPage << 14));
	switch (frm) {
		case SCR_HOB:
			file.open(fnam.c_str(),std::ios::binary);
			file.write((char*)hobHead,17);
			file.write(sptr, 0x1b00);
			file.close();
			break;
		case SCR_SCR:
			file.open(fnam.c_str(),std::ios::binary);
			file.write(sptr, 0x1b00);
			file.close();
			break;
		case SCR_BMP:
		case SCR_JPG:
		case SCR_PNG:
			if (img.isNull()) break;
			if (conf.scrShot.noBorder)
				img = img.copy((vid->bord.x - vid->lcut.x) * 2, vid->bord.y - vid->lcut.y,
					vid->scrn.x * 2, vid->scrn.y);
			img = img.scaled(img.width() / 2 * conf.vid.scale * comp->hw->xscale,
					img.height() * conf.vid.scale);
			img.save(QString(fnam.c_str()),fext.c_str());
			break;
	}
	setMessage("screenshot saved");
}

// video drawing

QList<xLed> leds;

void drawLeds(QPainter& pnt) {
	xLed* led;
	int x,y;
	int i;
	for (i = 0; i < leds.size(); i++) {
		led = &leds[i];
		if (led->showTime > 0) {
			led->showTime--;
			x = led->x;
			y = led->y;
			if (x < 0) x = pnt.device()->width() + x;
			if (y < 0) y = pnt.device()->height() + y;
			pnt.drawImage(x, y, QImage(led->imgName).scaled(16,16));
		}
	}
}

void addLed(int x, int y, QString name, int time) {
	xLed led;
	led.x = x;
	led.y = y;
	led.imgName = name;
	led.showTime = time;
	for (int i = 0; i < leds.size(); i++) {
		if (leds[i].imgName == name) {
			leds[i] = led;
			name.clear();
		}
	}
	if (!name.isEmpty()) {
		leds.append(led);
	}
}

void MainWin::setMessage(QString str, double dur) {
	msgTimer = (int)(dur * 50);
	msg = str;
}

void MainWin::updateSatellites() {
	if (block) return;
	Computer* comp = conf.prof.cur->zx;
// update rzx window
#ifdef HAVEZLIB
	emit s_rzx_upd(comp);
#endif
// update tape window
	if (comp->tape->on && !comp->tape->rec)
		emit s_tape_progress(comp->tape);
	if ((comp->tape->on && !comp->tape->rec) || comp->tape->blkChange || comp->tape->newBlock) {
		emit s_tape_upd(comp->tape);
		if (comp->tape->blkChange || comp->tape->newBlock) {
			emit s_tape_blk(comp->tape);
			comp->tape->blkChange = 0;
			comp->tape->newBlock = 0;
		}
	}
// update watcher
	emit s_watch_upd(comp);
}

// USER MENU

void MainWin::initUserMenu() {
	userMenu = new QMenu(this);
// submenu
	fileMenu = userMenu->addMenu(QIcon(":/images/fileopen.png"),"Open...");
	bookmarkMenu = userMenu->addMenu(QIcon(":/images/star.png"),"Bookmarks");
	profileMenu = userMenu->addMenu(QIcon(":/images/profile.png"),"Profiles");
	layoutMenu = userMenu->addMenu(QIcon(":/images/display.png"),"Layout");
	keyMenu = userMenu->addMenu(QIcon(":/images/keyboardzx.png"), "Keymap");
	resMenu = userMenu->addMenu(QIcon(":/images/shutdown.png"),"Reset");
	shdMenu = userMenu->addMenu(QIcon(":/images/shader.png"), "Shaders");
	palMenu = userMenu->addMenu(QIcon(":/images/palette.png"), "ZX palette");

	userMenu->addSeparator();
	userMenu->addAction(QIcon(":/images/tape.png"), "Tape player", this, SIGNAL(s_tape_show()));
	userMenu->addAction(QIcon(":/images/video.png"),"RZX player", this, SIGNAL(s_rzx_show()));
	userMenu->addSeparator();
	pckAct = userMenu->addAction(QIcon(":/images/keyboard.png"),"Grab keyboard");
	pckAct->setCheckable(true);
	userMenu->addAction(QIcon(":/images/keyboardzx.png"),"ZX Keyboard",this,SIGNAL(s_keywin_shide()));
	userMenu->addAction(QIcon(":/images/objective.png"),"Watcher", this, SIGNAL(s_watch_show()));
	userMenu->addAction(QIcon(":/images/bug.png"), "Debugger", this, SLOT(doDebug()));
	userMenu->addAction(QIcon(":/images/other.png"),"Options",this,SLOT(doOptions()));

	connect(bookmarkMenu,SIGNAL(triggered(QAction*)),this,SLOT(bookmarkSelected(QAction*)));
	connect(profileMenu,SIGNAL(triggered(QAction*)),this,SLOT(profileSelected(QAction*)));
	connect(layoutMenu,SIGNAL(triggered(QAction*)),this,SLOT(chLayout(QAction*)));
	connect(resMenu,SIGNAL(triggered(QAction*)),this,SLOT(reset(QAction*)));
	connect(fileMenu,SIGNAL(triggered(QAction*)),this,SLOT(umOpen(QAction*)));
	connect(shdMenu,SIGNAL(triggered(QAction*)),this,SLOT(shdSelected(QAction*)));
	connect(keyMenu,SIGNAL(triggered(QAction*)),this,SLOT(keySelected(QAction*)));
	connect(palMenu,SIGNAL(triggered(QAction*)),this,SLOT(palSelected(QAction*)));

	fileMenu->addAction(QIcon(":/images/memory.png"),"Snapshot")->setData(FG_SNAPSHOT);
	fileMenu->addAction(QIcon(":/images/tape.png"),"Tape")->setData(FG_TAPE);
	fileMenu->addAction(QIcon(":/images/floppy.png"),"Floppy")->setData(FH_DISKS);

	resMenu->addAction("default")->setData(RES_DEFAULT);
	resMenu->addSeparator();
	resMenu->addAction("ROMpage0")->setData(RES_128);
	resMenu->addAction("ROMpage1")->setData(RES_48);
	resMenu->addAction("ROMpage2")->setData(RES_SHADOW);
	resMenu->addAction("ROMpage3")->setData(RES_DOS);
#ifdef ISDEBUG
	userMenu->addSeparator();
	dbgMenu = userMenu->addMenu(QIcon(":/images/debuga.png"),"Debug");
	dbgMenu->addAction(QIcon(),QString("Save v9938 vram..."),this,SLOT(saveVRAM()));
	dbgMenu->addAction(QIcon(),QString("Save GB VRAM..."), this, SLOT(saveGBVRAM()));
//	dbgMenu->addAction(QIcon(),QString("Save GS RAM..."),this,SLOT(saveGSRAM()));
	dbgMenu->addAction(QIcon(),QString("Save NES PPU vram..."),this,SLOT(saveNESPPU()));
#endif
}

void MainWin::fillUserMenu() {
	// fill bookmark menu
	bookmarkMenu->clear();
	QAction* act;
	if (conf.bookmarkList.size() == 0) {
		bookmarkMenu->addAction("None")->setEnabled(false);
	} else {
		foreach(xBookmark bkm, conf.bookmarkList) {
			act = bookmarkMenu->addAction(QString::fromLocal8Bit(bkm.name.c_str()));
			act->setData(QVariant(QString::fromLocal8Bit(bkm.path.c_str())));
		}
	}
	// fill profile menu
	profileMenu->clear();
	foreach(xProfile* prf, conf.prof.list) {
		profileMenu->addAction(prf->name.c_str())->setData(prf->name.c_str());
	}
	// fill layout menu
	layoutMenu->clear();
	foreach(xLayout lay, conf.layList) {
		layoutMenu->addAction(lay.name.c_str())->setData(lay.name.c_str());
	}
	// fill keymaps menu
	keyMenu->clear();
	act = keyMenu->addAction("Default");
	act->setData("");
	act->setCheckable(true);
	if (conf.prof.cur) {
		if (conf.prof.cur->kmapName.empty()) act->setChecked(true);
		QDir dir(conf.path.confDir.c_str());
		QStringList lst = dir.entryList(QStringList() << "*.map",QDir::Files,QDir::Name);
		dir.setPath(dir.path().append("/keymaps/"));
		lst.append(dir.entryList(QStringList() << "*.map",QDir::Files,QDir::Name));
		lst.sort();
		foreach(QString str, lst) {
			act = keyMenu->addAction(str);
			act->setData(str);
			act->setCheckable(true);
			act->setChecked(conf.prof.cur->kmapName == std::string(str.toUtf8().data()));
		}
	}
	// fill shader menu
	shdMenu->clear();
	act = shdMenu->addAction("none");
	act->setData("");
	act->setCheckable(true);
	if (conf.vid.shader.empty()) act->setChecked(true);
#if defined(USEOPENGL) && !BLOCKGL
	if (conf.vid.shd_support) {
		QDir dir(conf.path.shdDir.c_str());
		QFileInfoList lst = dir.entryInfoList(QStringList() << "*.txt", QDir::Files, QDir::Name);
		foreach(QFileInfo inf, lst) {
			act = shdMenu->addAction(inf.fileName());
			act->setData(inf.fileName());
			act->setCheckable(true);
			act->setChecked(inf.fileName() == conf.vid.shader.c_str());
		}
	}
#endif
	// fill palette menu
	palMenu->clear();
	act = palMenu->addAction("default");
	act->setData("");
	act->setCheckable(true);
	if (conf.prof.cur->palette.empty()) act->setChecked(true);
	QDir dir(conf.path.palDir.c_str());
	QFileInfoList lst = dir.entryInfoList(QStringList() << "*.txt", QDir::Files, QDir::Name);
	foreach(QFileInfo inf, lst) {
		act = palMenu->addAction(inf.fileName());
		act->setData(inf.fileName());
		act->setCheckable(true);
		act->setChecked(inf.fileName() == conf.prof.cur->palette.c_str());
	}
}

// SLOTS

void MainWin::doOptions() {
	pause(true, PR_OPTS);
	emit s_options();
}

// Apply in the options dialog, with the dialog still open. The border size may
// have changed, and the window has to follow it at once - the frame is re-cut
// out of the whole raster, so the picture stays right even though the machine
// is paused and no new frame is coming.
void MainWin::optResize() {
	int bpl = bytesPerLine;			// the row length the buffer was written with
	updateWindow();
	// Apply can also change the machine or its layout, and the frame in the
	// buffer would then be read back at a row length it was not drawn with
	if (bytesPerLine != bpl)
		renderFrame();
	presentFrame();
}

void MainWin::optApply() {
//	relskip = 1;
//	comp = conf.prof.cur->zx;
	Computer* comp = conf.prof.cur->zx;
	fillUserMenu();
	updateWindow();
	loadPalette(conf.prof.cur);
#ifdef USENETWORK
	if (srv.serverPort() != conf.port) {
		closeServer();
		openServer();

	}
#endif
#if defined(USEOPENGL) && !BLOCKGL
	loadShader();
#endif
	emit s_tape_upd(comp->tape);
	pause(false, PR_OPTS);
}

void MainWin::doDebug() {
	conf.emu.fast = 0;
	pause(true, PR_DEBUG);
	conf.prof.cur->zx->flgDBG = 1;
	emit s_debug();
}

void MainWin::dbgReturn() {
	pause(false, PR_DEBUG);
	conf.prof.cur->zx->flgDBG = 0;
}

void MainWin::bookmarkSelected(QAction* act) {
	openMedia(act->data().toString(), FG_ALL, 0, conf.autorun);
	setFocus();
}

// One frame of the current machine, run from this thread. The image buffer is
// shared by every machine, so after a profile switch it still holds the frame
// the machine before drew - and the emulation may not be in a position to draw
// over it: with the options dialog open it is paused until the dialog closes.
//
// This deliberately steps the cpu rather than asking xThread::emuCycle() for a
// frame: that one is paced, fills the sound buffer and signals the frame on to
// the display, none of which a cosmetic redraw wants, and it stops dead while
// conf.emu.pause is set - which is exactly the case this exists for. emu_lock()
// is what keeps the two apart, the same way the profile switch above uses it.
void MainWin::renderFrame() {
	Computer* comp = conf.prof.cur->zx;
	vid_clear_image();			// whatever is in there was not drawn by this machine
	if (!comp || comp->flgDBG) return;	// the debugger owns the machine, don't step it
	// a frame is some 20000 opcodes. The count is only here to stop a machine
	// that never finishes one - a profile still on "Dummy" hardware, say
	int guard = 1 << 19;
	emu_lock();
	comp->flgFRM = 0;
	while (!comp->flgFRM && !comp->flgBRK && (guard-- > 0))
		compExec(comp);
	comp->flgFRM = 0;			// the frame is ours, not the pacer's
	// A breakpoint hit inside this one cosmetic frame is dropped on purpose:
	// emuCycle() would only clear the flag without acting on it, and the
	// machine runs into the same breakpoint again as soon as it goes on
	comp->flgBRK = 0;
	emu_unlock();
}

void MainWin::onPrfChange() {
	Computer* comp = conf.prof.cur->zx;
	comp->tape->detectOn = conf.tape.autostart;
	comp->tape->autorew = conf.tape.rewind;
	if (comp->flgFRN) {
		// loadPalette(conf.prof.cur);		// already loaded for each profile
		compReset(comp, RES_DEFAULT);
		comp->flgFRN = 0;
	}
	emit s_keywin_upd(comp->keyb);
	vid_upd_scale();
	updateWindow();
	// hasPicture: at start-up there is nothing in the buffer to clean up after,
	// and the machine must not be stepped before the event loop is up
	if (hasPicture) {
		renderFrame();
		presentFrame();
	}
//	saveConfig();
//	emit s_prf_change(conf.prof.cur);
//	conf.prof.changed = 1;
}

void MainWin::profileSelected(QAction* act) {
	std::string str = QString(act->data().toByteArray()).toStdString();
	emu_lock();		// onPrfChange resets the machine, keep it out of the emulation too
	prfSetCurrent(str);
	onPrfChange();
	emu_unlock();
}

void MainWin::reset(QAction* act) {
	Computer* comp = conf.prof.cur->zx;
	emit s_rzx_stop();
	emu_lock();		// reset re-inits the hardware
	compReset(comp,act->data().toInt());
	emu_unlock();
}

void MainWin::chLayout(QAction* act) {
	std::string str = QString(act->data().toByteArray()).toStdString();
	prfSetLayout(NULL, str);
	prfSave();
	updateWindow();
}

void MainWin::umOpen(QAction* act) {
	openMedia(QString(), act->data().toInt(), -1, conf.autorun);
}

void MainWin::keySelected(QAction* act) {
	QString str = act->data().toString();
	if (str.isEmpty()) {
		conf.prof.cur->kmapName.clear();
	} else {
		conf.prof.cur->kmapName = std::string(str.toUtf8().data());
	}
	prfSave();
	loadKeys();
}

void MainWin::palSelected(QAction* act) {
	QString str = act->data().toString();
	if (str.isEmpty()) {
		conf.prof.cur->palette.clear();
	} else {
		conf.prof.cur->palette = std::string(str.toUtf8().data());
	}
	prfSave();
	loadPalette(conf.prof.cur);
}

// debug stufffff

void MainWin::saveVRAM() {
	QString path = QFileDialog::getSaveFileName(this,"Save VRAM");
	if (path.isEmpty()) return;
	QFile file(path);
	xColor xcol;
	Computer* comp = conf.prof.cur->zx;
	if (file.open(QFile::WriteOnly)) {
		file.write((char*)comp->vid->ram, 0x20000);
		file.write((char*)comp->vid->reg, 64);
		for (int i = 0; i < 16; i++) {
			xcol = vid_get_col(comp->vid, i);
			file.putChar(xcol.r);
			file.putChar(xcol.g);
			file.putChar(xcol.b);
		}

		file.close();
	}
}

void MainWin::saveGBVRAM() {
	QString path = QFileDialog::getSaveFileName(this,"Save GB VRAM");
	if (path.isEmpty()) return;
	QFile file(path);
	Computer* comp = conf.prof.cur->zx;
	if (file.open(QFile::WriteOnly)) {
		file.write((char*)comp->vid->ram, 0x2000);
		file.write((char*)comp->gb.iomap, 0x80);
		file.close();
	}
}

void MainWin::saveNESPPU() {
	QString path = QFileDialog::getSaveFileName(this,"Save GB VRAM");
	if (path.isEmpty()) return;
	QFile file(path);
	Computer* comp = conf.prof.cur->zx;
	if (file.open(QFile::WriteOnly)) {
		file.write((char*)comp->vid->ram, 0x4000);
		file.write((char*)comp->vid->oam, 0x100);
		file.close();
	}
}

void MainWin::debugAction() {
	sndDebug();
}
