[MACHINE]

current = Pentagon
memory = 128
cpu.type = Z80
cpu.frq = 3546900
frq.mul = 1.000000
scrp.wait = no
contio = yes
contmem = yes

[ROMSET]

current = ZX Spectrum 128K + TR-DOS
reset = basic128

[VIDEO]

geometry = ZX 128K
4t-border = yes
ULAplus = no
contPattern = 1
earlyTiming = yes
DDpal = no
palette = xpeccy.txt

[SOUND]

chip1 = 1
chip1.stereo = 2
chip1.frq = 1.773400
chip2 = 1
chip2.stereo = 2
chip2.frq = 1.773400
chip3 = 1
chip3.stereo = 0
chip3.frq = 1.000000
ts.type = 1
gs = no
gs.reset = yes
gs.stereo = 1
soundrive_type = 0
saa = no

[TAPE]

speed = 100

[DISK]

type = 1

[INPUT]

mouse = yes
mouse.wheel = no
mouse.swapButtons = no
mouse.sensitivity = 1.000000
joy.extbuttons = yes
gamepad.map = kempston.pad
keymap = keys.map

[IDE]

iface = 0
master.type = 0
slave.type = 0
